In [1]:
### Extract file in /Users/wenjun/Downloads/JPXData/AGM

import os
import zipfile
import shutil
from pathlib import Path

# 设置源目录和目标目录
source_dir = "/Users/wenjun/Downloads/JPXData/AGM"
target_dir = "/Users/wenjun/Downloads/JPXData/AGM/XBRL"

# 确保目标目录存在
os.makedirs(target_dir, exist_ok=True)

def extract_xbrl_from_zip(zip_path, target_dir):
    """从ZIP文件中提取XBRL文件"""
    try:
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            # 获取ZIP文件中的所有文件列表
            file_list = zip_ref.namelist()
            
            # 查找XBRL文件
            xbrl_files = [f for f in file_list if f.endswith('.xbrl')]
            
            if not xbrl_files:
                print(f"在 {zip_path} 中没有找到XBRL文件")
                return
            
            # 获取zip文件的基本名称（不含扩展名）
            zip_base_name = os.path.splitext(os.path.basename(zip_path))[0]
            
            # 构建新的目标文件名
            target_path = os.path.join(target_dir, f"{zip_base_name}.xbrl")
            
            # 提取第一个XBRL文件并重命名
            with zip_ref.open(xbrl_files[0]) as source, open(target_path, 'wb') as target:
                shutil.copyfileobj(source, target)
            print(f"已提取并重命名为: {zip_base_name}.xbrl")
                
    except Exception as e:
        print(f"处理 {zip_path} 时出错: {str(e)}")

def main():
    # 获取所有ZIP文件
    zip_files = [f for f in os.listdir(source_dir) if f.endswith('.zip')]
    
    if not zip_files:
        print(f"在 {source_dir} 中没有找到ZIP文件")
        return
    
    print(f"找到 {len(zip_files)} 个ZIP文件")
    
    # 处理每个ZIP文件
    for zip_file in zip_files:
        zip_path = os.path.join(source_dir, zip_file)
        print(f"\n处理: {zip_file}")
        extract_xbrl_from_zip(zip_path, target_dir)

if __name__ == "__main__":
    main()

找到 505 个ZIP文件

处理: 41920_20250327.zip
已提取并重命名为: 41920_20250327.xbrl

处理: 25020_20250327.zip
已提取并重命名为: 25020_20250327.xbrl

处理: 89140_20250327.zip
已提取并重命名为: 89140_20250327.xbrl

处理: 66350_20250328.zip
已提取并重命名为: 66350_20250328.xbrl

处理: 34750_20250131.zip
已提取并重命名为: 34750_20250131.xbrl

处理: 291A0_20250327.zip
已提取并重命名为: 291A0_20250327.xbrl

处理: 56180_20250327.zip
已提取并重命名为: 56180_20250327.xbrl

处理: 60490_20250131.zip
已提取并重命名为: 60490_20250131.xbrl

处理: 99720_20250228.zip
已提取并重命名为: 99720_20250228.xbrl

处理: 33460_20250225.zip
已提取并重命名为: 33460_20250225.xbrl

处理: 228A0_20250228.zip
已提取并重命名为: 228A0_20250228.xbrl

处理: 39640_20250326.zip
已提取并重命名为: 39640_20250326.xbrl

处理: 70440_20250327.zip
已提取并重命名为: 70440_20250327.xbrl

处理: 25870_20250328.zip
已提取并重命名为: 25870_20250328.xbrl

处理: 34800_20250129.zip
已提取并重命名为: 34800_20250129.xbrl

处理: 70370_20250321.zip
已提取并重命名为: 70370_20250321.xbrl

处理: 59460_20250327.zip
已提取并重命名为: 59460_20250327.xbrl

处理: 43770_20250327.zip
已提取并重命名为: 43770_20250327.xbrl

处理: 92790_20250203.zip
已提取并重命名为: 92790_20250203.xbrl

处理: 56190_20250328.zip
已提取并重命名为: 56190_20250328.xbrl

处理: 63260_20250324.zip
已提取并重命名为: 63260_20250324.xbrl

处理: 42350_20250328.zip
已提取并重命名为: 42350_20250328.xbrl

处理: 89290_20250327.zip
已提取并重命名为: 89290_20250327.xbrl

处理: 71770_20250325.zip
已提取并重命名为: 71770_20250325.xbrl

处理: 43720_20250328.zip
已提取并重命名为: 43720_20250328.xbrl

处理: 36730_20250324.zip
已提取并重命名为: 36730_20250324.xbrl

处理: 55910_20250328.zip
已提取并重命名为: 55910_20250328.xbrl

处理: 59430_20250328.zip
已提取并重命名为: 59430_20250328.xbrl

处理: 34740_20250328.zip
已提取并重命名为: 34740_20250328.xbrl

处理: 23210_20250318.zip
已提取并重命名为: 23210_20250318.xbrl

处理: 64250_20250327.zip
已提取并重命名为: 64250_20250327.xbrl

处理: 33860_20250327.zip
已提取并重命名为: 33860_20250327.xbrl

处理: 40990_20250328.zip
已提取并重命名为: 40990_20250328.xbrl

处理: 36590_20250327.zip
已提取并重命名为: 36590_20250327.xbrl

处理: 50150_20250326.zip
已提取并重命名为: 50150_20250326.xbrl

处理: 39280_20250328.zip
已提取并重命名为: 39280_20250328.xbrl

处理: 44040_20250327.zip
已提取并重命名为: 44040_20250327.xbrl

处理: 44380_20250328.zip
已提取并重命名为: 44380_20250328.xbrl

处理: 41660_20250327.zip
已提取并重命名为: 41660_20250327.xbrl

处理: 47220_20250326.zip
已提取并重命名为: 47220_20250326.xbrl

处理: 44930_20250327.zip
已提取并重命名为: 44930_20250327.xbrl

处理: 261A0_20250327.zip
已提取并重命名为: 261A0_20250327.xbrl

处理: 49110_20250327.zip
已提取并重命名为: 49110_20250327.xbrl

处理: 51260_20250325.zip
已提取并重命名为: 51260_20250325.xbrl

处理: 27340_20250225.zip
已提取并重命名为: 27340_20250225.xbrl

处理: 89180_20250214.zip
已提取并重命名为: 89180_20250214.xbrl

处理: 29320_20250328.zip
已提取并重命名为: 29320_20250328.xbrl

处理: 34160_20250327.zip
已提取并重命名为: 34160_20250327.xbrl

处理: 72680_20250131.zip
已提取并重命名为: 72680_20250131.xbrl

处理: 70340_20250131.zip
已提取并重命名为: 70340_20250131.xbrl

处理: 62650_20250326.zip
已提取并重命名为: 62650_20250326.xbrl

处理: 62760_20250327.zip
已提取并重命名为: 62760_20250327.xbrl

处理: 94410_20250327.zip
已提取并重命名为: 94410_20250327.xbrl

处理: 36640_20250327.zip
已提取并重命名为: 36640_20250327.xbrl

处理: 40190_20250328.zip
已提取并重命名为: 40190_20250328.xbrl

处理: 45640_20250218.zip
已提取并重命名为: 45640_20250218.xbrl

处理: 93430_20250328.zip
已提取并重命名为: 93430_20250328.xbrl

处理: 41870_20250306.zip
已提取并重命名为: 41870_20250306.xbrl

处理: 44800_20250326.zip
已提取并重命名为: 44800_20250326.xbrl

处理: 74220_20250218.zip
已提取并重命名为: 74220_20250218.xbrl

处理: 85080_20250327.zip
已提取并重命名为: 85080_20250327.xbrl

处理: 30470_20250321.zip
已提取并重命名为: 30470_20250321.xbrl

处理: 39130_20250326.zip
已提取并重命名为: 39130_20250326.xbrl

处理: 72440_20250328.zip
已提取并重命名为: 72440_20250328.xbrl

处理: 73140_20250328.zip
已提取并重命名为: 73140_20250328.xbrl

处理: 260A0_20250327.zip
已提取并重命名为: 260A0_20250327.xbrl

处理: 14350_20250328.zip
已提取并重命名为: 14350_20250328.xbrl

处理: 36710_20250328.zip
已提取并重命名为: 36710_20250328.xbrl

处理: 89230_20250227.zip
已提取并重命名为: 89230_20250227.xbrl

处理: 92500_20250228.zip
已提取并重命名为: 92500_20250228.xbrl

处理: 334A0_20250328.zip
已提取并重命名为: 334A0_20250328.xbrl

处理: 24990_20250328.zip
已提取并重命名为: 24990_20250328.xbrl

处理: 50390_20250328.zip
已提取并重命名为: 50390_20250328.xbrl

处理: 62660_20250327.zip
已提取并重命名为: 62660_20250327.xbrl

处理: 93450_20250327.zip
已提取并重命名为: 93450_20250327.xbrl

处理: 80790_20250131.zip
已提取并重命名为: 80790_20250131.xbrl

处理: 37380_20250207.zip
已提取并重命名为: 37380_20250207.xbrl

处理: 68710_20250328.zip
已提取并重命名为: 68710_20250328.xbrl

处理: 23300_20250328.zip
已提取并重命名为: 23300_20250328.xbrl

处理: 62170_20250303.zip
已提取并重命名为: 62170_20250303.xbrl

处理: 79850_20250304.zip
已提取并重命名为: 79850_20250304.xbrl

处理: 78410_20250328.zip
已提取并重命名为: 78410_20250328.xbrl

处理: 51320_20250127.zip
已提取并重命名为: 51320_20250127.xbrl

处理: 64740_20250228.zip
已提取并重命名为: 64740_20250228.xbrl

处理: 55270_20250227.zip
已提取并重命名为: 55270_20250227.xbrl

处理: 44280_20250328.zip
已提取并重命名为: 44280_20250328.xbrl

处理: 55630_20250327.zip
已提取并重命名为: 55630_20250327.xbrl

处理: 96220_20250328.zip
已提取并重命名为: 96220_20250328.xbrl

处理: 65740_20250305.zip
已提取并重命名为: 65740_20250305.xbrl

处理: 34540_20250228.zip
已提取并重命名为: 34540_20250228.xbrl

处理: 79830_20250130.zip
已提取并重命名为: 79830_20250130.xbrl

处理: 34910_20250131.zip
已提取并重命名为: 34910_20250131.xbrl

处理: 45790_20250326.zip
已提取并重命名为: 45790_20250326.xbrl

处理: 21980_20250129.zip
已提取并重命名为: 21980_20250129.xbrl

处理: 21690_20250327.zip
已提取并重命名为: 21690_20250327.xbrl

处理: 18970_20250328.zip
已提取并重命名为: 18970_20250328.xbrl

处理: 50700_20250328.zip
已提取并重命名为: 50700_20250328.xbrl

处理: 41070_20250328.zip
已提取并重命名为: 41070_20250328.xbrl

处理: 70430_20250327.zip
已提取并重命名为: 70430_20250327.xbrl

处理: 66330_20250327.zip
已提取并重命名为: 66330_20250327.xbrl

处理: 22060_20250327.zip
已提取并重命名为: 22060_20250327.xbrl

处理: 219A0_20250127.zip
已提取并重命名为: 219A0_20250127.xbrl

处理: 52460_20250228.zip
已提取并重命名为: 52460_20250228.xbrl

处理: 28300_20250221.zip
已提取并重命名为: 28300_20250221.xbrl

处理: 43750_20250328.zip
已提取并重命名为: 43750_20250328.xbrl

处理: 78270_20250131.zip
已提取并重命名为: 78270_20250131.xbrl

处理: 68170_20250327.zip
已提取并重命名为: 68170_20250327.xbrl

处理: 290A0_20250326.zip
已提取并重命名为: 290A0_20250326.xbrl

处理: 298A0_20250327.zip
已提取并重命名为: 298A0_20250327.xbrl

处理: 43740_20250327.zip
已提取并重命名为: 43740_20250327.xbrl

处理: 22110_20250326.zip
已提取并重命名为: 22110_20250326.xbrl

处理: 81650_20250328.zip
已提取并重命名为: 81650_20250328.xbrl

处理: 30400_20250327.zip
已提取并重命名为: 30400_20250327.xbrl

处理: 40530_20250328.zip
已提取并重命名为: 40530_20250328.xbrl

处理: 95220_20250226.zip
已提取并重命名为: 95220_20250226.xbrl

处理: 79760_20250328.zip
已提取并重命名为: 79760_20250328.xbrl

处理: 87980_20250328.zip
已提取并重命名为: 87980_20250328.xbrl

处理: 71120_20250328.zip
已提取并重命名为: 71120_20250328.xbrl

处理: 43710_20250328.zip
已提取并重命名为: 43710_20250328.xbrl

处理: 81130_20250321.zip
已提取并重命名为: 81130_20250321.xbrl

处理: 94250_20250131.zip
已提取并重命名为: 94250_20250131.xbrl

处理: 89170_20250130.zip
已提取并重命名为: 89170_20250130.xbrl

处理: 49710_20250326.zip
已提取并重命名为: 49710_20250326.xbrl

处理: 52430_20250226.zip
已提取并重命名为: 52430_20250226.xbrl

处理: 39740_20250131.zip
已提取并重命名为: 39740_20250131.xbrl

处理: 73590_20250328.zip
已提取并重命名为: 73590_20250328.xbrl

处理: 46730_20250228.zip
已提取并重命名为: 46730_20250228.xbrl

处理: 39500_20250327.zip
已提取并重命名为: 39500_20250327.xbrl

处理: 97310_20250328.zip
已提取并重命名为: 97310_20250328.xbrl

处理: 35470_20250228.zip
已提取并重命名为: 35470_20250228.xbrl

处理: 39470_20250327.zip
已提取并重命名为: 39470_20250327.xbrl

处理: 95580_20250225.zip
已提取并重命名为: 95580_20250225.xbrl

处理: 91630_20250131.zip
已提取并重命名为: 91630_20250131.xbrl

处理: 51390_20250328.zip
已提取并重命名为: 51390_20250328.xbrl

处理: 42930_20250327.zip
已提取并重命名为: 42930_20250327.xbrl

处理: 51840_20250328.zip
已提取并重命名为: 51840_20250328.xbrl

处理: 41510_20250321.zip
已提取并重命名为: 41510_20250321.xbrl

处理: 93690_20250228.zip
已提取并重命名为: 93690_20250228.xbrl

处理: 82150_20250123.zip
已提取并重命名为: 82150_20250123.xbrl

处理: 60780_20250328.zip
已提取并重命名为: 60780_20250328.xbrl

处理: 30640_20250327.zip
已提取并重命名为: 30640_20250327.xbrl

处理: 38040_20250131.zip
已提取并重命名为: 38040_20250131.xbrl

处理: 79440_20250327.zip
已提取并重命名为: 79440_20250327.xbrl

处理: 39070_20250227.zip
已提取并重命名为: 39070_20250227.xbrl

处理: 22680_20250321.zip
已提取并重命名为: 22680_20250321.xbrl

处理: 39940_20250227.zip
已提取并重命名为: 39940_20250227.xbrl

处理: 23110_20250325.zip
已提取并重命名为: 23110_20250325.xbrl

处理: 79560_20250328.zip
已提取并重命名为: 79560_20250328.xbrl

处理: 40720_20250326.zip
已提取并重命名为: 40720_20250326.xbrl

处理: 27520_20250328.zip
已提取并重命名为: 27520_20250328.xbrl

处理: 66120_20250328.zip
已提取并重命名为: 66120_20250328.xbrl

处理: 43870_20250226.zip
已提取并重命名为: 43870_20250226.xbrl

处理: 41890_20250328.zip
已提取并重命名为: 41890_20250328.xbrl

处理: 48920_20250326.zip
已提取并重命名为: 48920_20250326.xbrl

处理: 66630_20250319.zip
已提取并重命名为: 66630_20250319.xbrl

处理: 40580_20250325.zip
已提取并重命名为: 40580_20250325.xbrl

处理: 63090_20250203.zip
已提取并重命名为: 63090_20250203.xbrl

处理: 41970_20250228.zip
已提取并重命名为: 41970_20250228.xbrl

处理: 31390_20250227.zip
已提取并重命名为: 31390_20250227.xbrl

处理: 70380_20250328.zip
已提取并重命名为: 70380_20250328.xbrl

处理: 45720_20250328.zip
已提取并重命名为: 45720_20250328.xbrl

处理: 64110_20250327.zip
已提取并重命名为: 64110_20250327.xbrl

处理: 79460_20250306.zip
已提取并重命名为: 79460_20250306.xbrl

处理: 68380_20250204.zip
已提取并重命名为: 68380_20250204.xbrl

处理: 39980_20250328.zip
已提取并重命名为: 39980_20250328.xbrl

处理: 55420_20250328.zip
已提取并重命名为: 55420_20250328.xbrl

处理: 62680_20250327.zip
已提取并重命名为: 62680_20250327.xbrl

处理: 32480_20250130.zip
已提取并重命名为: 32480_20250130.xbrl

处理: 70930_20250327.zip
已提取并重命名为: 70930_20250327.xbrl

处理: 62690_20250328.zip
已提取并重命名为: 62690_20250328.xbrl

处理: 72720_20250327.zip
已提取并重命名为: 72720_20250327.xbrl

处理: 23150_20250131.zip
已提取并重命名为: 23150_20250131.xbrl

处理: 17180_20250327.zip
已提取并重命名为: 17180_20250327.xbrl

处理: 96030_20250130.zip
已提取并重命名为: 96030_20250130.xbrl

处理: 17240_20250328.zip
已提取并重命名为: 17240_20250328.xbrl

处理: 73090_20250328.zip
已提取并重命名为: 73090_20250328.xbrl

处理: 47120_20250326.zip
已提取并重命名为: 47120_20250326.xbrl

处理: 29140_20250327.zip
已提取并重命名为: 29140_20250327.xbrl

处理: 52410_20250328.zip
已提取并重命名为: 52410_20250328.xbrl

处理: 61800_20250321.zip
已提取并重命名为: 61800_20250321.xbrl

处理: 21700_20250327.zip
已提取并重命名为: 21700_20250327.xbrl

处理: 145A0_20250327.zip
已提取并重命名为: 145A0_20250327.xbrl

处理: 62500_20250328.zip
已提取并重命名为: 62500_20250328.xbrl

处理: 27880_20250328.zip
已提取并重命名为: 27880_20250328.xbrl

处理: 49190_20250328.zip
已提取并重命名为: 49190_20250328.xbrl

处理: 187A0_20250110.zip
已提取并重命名为: 187A0_20250110.xbrl

处理: 138A0_20250227.zip
已提取并重命名为: 138A0_20250227.xbrl

处理: 70810_20250328.zip
已提取并重命名为: 70810_20250328.xbrl

处理: 99730_20250327.zip
已提取并重命名为: 99730_20250327.xbrl

处理: 80950_20250306.zip
已提取并重命名为: 80950_20250306.xbrl

处理: 82070_20250328.zip
已提取并重命名为: 82070_20250328.xbrl

处理: 36330_20250321.zip
已提取并重命名为: 36330_20250321.xbrl

处理: 64000_20250328.zip
已提取并重命名为: 64000_20250328.xbrl

处理: 32760_20250326.zip
已提取并重命名为: 32760_20250326.xbrl

处理: 89950_20250205.zip
已提取并重命名为: 89950_20250205.xbrl

处理: 40040_20250328.zip
已提取并重命名为: 40040_20250328.xbrl

处理: 42580_20250328.zip
已提取并重命名为: 42580_20250328.xbrl

处理: 32770_20250328.zip
已提取并重命名为: 32770_20250328.xbrl

处理: 88940_20250131.zip
已提取并重命名为: 88940_20250131.xbrl

处理: 52420_20250328.zip
已提取并重命名为: 52420_20250328.xbrl

处理: 53410_20250228.zip
已提取并重命名为: 53410_20250228.xbrl

处理: 39760_20250204.zip
已提取并重命名为: 39760_20250204.xbrl

处理: 212A0_20250131.zip
已提取并重命名为: 212A0_20250131.xbrl

处理: 23010_20250131.zip
已提取并重命名为: 23010_20250131.xbrl

处理: 32610_20250327.zip
已提取并重命名为: 32610_20250327.xbrl

处理: 93130_20250303.zip
已提取并重命名为: 93130_20250303.xbrl

处理: 36530_20250131.zip
已提取并重命名为: 36530_20250131.xbrl

处理: 13830_20250131.zip
已提取并重命名为: 13830_20250131.xbrl

处理: 50270_20250328.zip
已提取并重命名为: 50270_20250328.xbrl

处理: 62780_20250327.zip
已提取并重命名为: 62780_20250327.xbrl

处理: 24910_20250326.zip
已提取并重命名为: 24910_20250326.xbrl

处理: 36560_20250328.zip
已提取并重命名为: 36560_20250328.xbrl

处理: 27210_20250328.zip
已提取并重命名为: 27210_20250328.xbrl

处理: 58510_20250327.zip
已提取并重命名为: 58510_20250327.xbrl

处理: 72270_20250228.zip
已提取并重命名为: 72270_20250228.xbrl

处理: 18400_20250129.zip
已提取并重命名为: 18400_20250129.xbrl

处理: 55890_20250327.zip
已提取并重命名为: 55890_20250327.xbrl

处理: 39090_20250325.zip
已提取并重命名为: 39090_20250325.xbrl

处理: 23750_20250131.zip
已提取并重命名为: 23750_20250131.xbrl

处理: 49920_20250227.zip
已提取并重命名为: 49920_20250227.xbrl

处理: 65580_20250227.zip
已提取并重命名为: 65580_20250227.xbrl

处理: 47720_20250326.zip
已提取并重命名为: 47720_20250326.xbrl

处理: 60990_20250325.zip
已提取并重命名为: 60990_20250325.xbrl

处理: 30890_20250227.zip
已提取并重命名为: 30890_20250227.xbrl

处理: 40120_20250325.zip
已提取并重命名为: 40120_20250325.xbrl

处理: 48830_20250328.zip
已提取并重命名为: 48830_20250328.xbrl

处理: 40740_20250328.zip
已提取并重命名为: 40740_20250328.xbrl

处理: 36230_20250326.zip
已提取并重命名为: 36230_20250326.xbrl

处理: 74220_20250318.zip
已提取并重命名为: 74220_20250318.xbrl

处理: 93390_20250328.zip
已提取并重命名为: 93390_20250328.xbrl

处理: 29700_20250327.zip
已提取并重命名为: 29700_20250327.xbrl

处理: 58420_20250325.zip
已提取并重命名为: 58420_20250325.xbrl

处理: 29340_20250227.zip
已提取并重命名为: 29340_20250227.xbrl

处理: 39400_20250327.zip
已提取并重命名为: 39400_20250327.xbrl

处理: 63610_20250327.zip
已提取并重命名为: 63610_20250327.xbrl

处理: 44500_20250327.zip
已提取并重命名为: 44500_20250327.xbrl

处理: 91730_20250327.zip
已提取并重命名为: 91730_20250327.xbrl

处理: 68660_20250228.zip
已提取并重命名为: 68660_20250228.xbrl

处理: 75180_20250219.zip
已提取并重命名为: 75180_20250219.xbrl

处理: 51100_20250328.zip
已提取并重命名为: 51100_20250328.xbrl

处理: 45930_20250327.zip
已提取并重命名为: 45930_20250327.xbrl

处理: 68350_20250328.zip
已提取并重命名为: 68350_20250328.xbrl

处理: 62230_20250328.zip
已提取并重命名为: 62230_20250328.xbrl

处理: 21950_20250328.zip
已提取并重命名为: 21950_20250328.xbrl

处理: 92510_20250131.zip
已提取并重命名为: 92510_20250131.xbrl

处理: 78310_20250203.zip
已提取并重命名为: 78310_20250203.xbrl

处理: 62350_20250326.zip
已提取并重命名为: 62350_20250326.xbrl

处理: 60540_20250327.zip
已提取并重命名为: 60540_20250327.xbrl

处理: 24610_20250327.zip
已提取并重命名为: 24610_20250327.xbrl

处理: 92370_20250131.zip
已提取并重命名为: 92370_20250131.xbrl

处理: 97550_20250327.zip
已提取并重命名为: 97550_20250327.xbrl

处理: 73600_20250226.zip
已提取并重命名为: 73600_20250226.xbrl

处理: 49270_20250327.zip
已提取并重命名为: 49270_20250327.xbrl

处理: 78040_20250129.zip
已提取并重命名为: 78040_20250129.xbrl

处理: 58190_20250324.zip
已提取并重命名为: 58190_20250324.xbrl

处理: 38560_20250221.zip
已提取并重命名为: 38560_20250221.xbrl

处理: 46410_20250328.zip
已提取并重命名为: 46410_20250328.xbrl

处理: 42640_20250328.zip
已提取并重命名为: 42640_20250328.xbrl

处理: 281A0_20250328.zip
已提取并重命名为: 281A0_20250328.xbrl

处理: 21600_20250328.zip
已提取并重命名为: 21600_20250328.xbrl

处理: 76250_20250324.zip
已提取并重命名为: 76250_20250324.xbrl

处理: 41680_20250328.zip
已提取并重命名为: 41680_20250328.xbrl

处理: 58680_20250328.zip
已提取并重命名为: 58680_20250328.xbrl

处理: 34190_20250130.zip
已提取并重命名为: 34190_20250130.xbrl

处理: 49960_20250203.zip
已提取并重命名为: 49960_20250203.xbrl

处理: 73880_20250305.zip
已提取并重命名为: 73880_20250305.xbrl

处理: 215A0_20250129.zip
已提取并重命名为: 215A0_20250129.xbrl

处理: 70820_20250327.zip
已提取并重命名为: 70820_20250327.xbrl

处理: 63280_20250328.zip
已提取并重命名为: 63280_20250328.xbrl

处理: 60760_20250226.zip
已提取并重命名为: 60760_20250226.xbrl

处理: 72380_20250303.zip
已提取并重命名为: 72380_20250303.xbrl

处理: 78490_20250328.zip
已提取并重命名为: 78490_20250328.xbrl

处理: 35660_20250328.zip
已提取并重命名为: 35660_20250328.xbrl

处理: 46160_20250228.zip
已提取并重命名为: 46160_20250228.xbrl

处理: 34360_20250328.zip
已提取并重命名为: 34360_20250328.xbrl

处理: 30380_20250131.zip
已提取并重命名为: 30380_20250131.xbrl

处理: 65460_20250328.zip
已提取并重命名为: 65460_20250328.xbrl

处理: 96750_20250131.zip
已提取并重命名为: 96750_20250131.xbrl

处理: 43610_20250221.zip
已提取并重命名为: 43610_20250221.xbrl

处理: 65370_20250327.zip
已提取并重命名为: 65370_20250327.xbrl

处理: 32660_20250306.zip
已提取并重命名为: 32660_20250306.xbrl

处理: 43560_20250327.zip
已提取并重命名为: 43560_20250327.xbrl

处理: 64810_20250317.zip
已提取并重命名为: 64810_20250317.xbrl

处理: 77160_20250325.zip
已提取并重命名为: 77160_20250325.xbrl

处理: 73470_20250327.zip
已提取并重命名为: 73470_20250327.xbrl

处理: 92540_20250130.zip
已提取并重命名为: 92540_20250130.xbrl

处理: 46270_20250130.zip
已提取并重命名为: 46270_20250130.xbrl

处理: 66940_20250328.zip
已提取并重命名为: 66940_20250328.xbrl

处理: 286A0_20250328.zip
已提取并重命名为: 286A0_20250328.xbrl

处理: 46310_20250328.zip
已提取并重命名为: 46310_20250328.xbrl

处理: 52180_20250131.zip
已提取并重命名为: 52180_20250131.xbrl

处理: 93840_20250327.zip
已提取并重命名为: 93840_20250327.xbrl

处理: 42500_20250228.zip
已提取并重命名为: 42500_20250228.xbrl

处理: 36280_20250220.zip
已提取并重命名为: 36280_20250220.xbrl

处理: 49790_20250327.zip
已提取并重命名为: 49790_20250327.xbrl

处理: 47840_20250321.zip
已提取并重命名为: 47840_20250321.xbrl

处理: 26930_20250328.zip
已提取并重命名为: 26930_20250328.xbrl

处理: 70610_20250327.zip
已提取并重命名为: 70610_20250327.xbrl

处理: 70630_20250106.zip
已提取并重命名为: 70630_20250106.xbrl

处理: 43780_20250130.zip
已提取并重命名为: 43780_20250130.xbrl

处理: 65330_20250327.zip
已提取并重命名为: 65330_20250327.xbrl

处理: 61710_20250324.zip
已提取并重命名为: 61710_20250324.xbrl

处理: 71310_20250131.zip
已提取并重命名为: 71310_20250131.xbrl

处理: 31210_20250131.zip
已提取并重命名为: 31210_20250131.xbrl

处理: 51360_20250203.zip
已提取并重命名为: 51360_20250203.xbrl

处理: 43790_20250328.zip
已提取并重命名为: 43790_20250328.xbrl

处理: 48110_20250328.zip
已提取并重命名为: 48110_20250328.xbrl

处理: 14490_20250328.zip
已提取并重命名为: 14490_20250328.xbrl

处理: 43040_20250228.zip
已提取并重命名为: 43040_20250228.xbrl

处理: 58360_20250328.zip
已提取并重命名为: 58360_20250328.xbrl

处理: 92360_20250129.zip
已提取并重命名为: 92360_20250129.xbrl

处理: 33220_20250110.zip
已提取并重命名为: 33220_20250110.xbrl

处理: 46660_20250204.zip
已提取并重命名为: 46660_20250204.xbrl

处理: 79570_20250328.zip
已提取并重命名为: 79570_20250328.xbrl

处理: 51050_20250328.zip
已提取并重命名为: 51050_20250328.xbrl

处理: 33500_20250326.zip
已提取并重命名为: 33500_20250326.xbrl

处理: 44410_20250130.zip
已提取并重命名为: 44410_20250130.xbrl

处理: 77760_20250327.zip
已提取并重命名为: 77760_20250327.xbrl

处理: 79970_20250228.zip
已提取并重命名为: 79970_20250228.xbrl

处理: 48800_20250131.zip
已提取并重命名为: 48800_20250131.xbrl

处理: 49670_20250220.zip
已提取并重命名为: 49670_20250220.xbrl

处理: 31030_20250212.zip
已提取并重命名为: 31030_20250212.xbrl

处理: 79650_20250221.zip
已提取并重命名为: 79650_20250221.xbrl

处理: 40130_20250321.zip
已提取并重命名为: 40130_20250321.xbrl

处理: 95430_20250327.zip
已提取并重命名为: 95430_20250327.xbrl

处理: 45820_20250326.zip
已提取并重命名为: 45820_20250326.xbrl

处理: 61360_20250225.zip
已提取并重命名为: 61360_20250225.xbrl

处理: 45830_20250328.zip
已提取并重命名为: 45830_20250328.xbrl

处理: 70480_20250327.zip
已提取并重命名为: 70480_20250327.xbrl

处理: 21930_20250328.zip
已提取并重命名为: 21930_20250328.xbrl

处理: 72650_20250129.zip
已提取并重命名为: 72650_20250129.xbrl

处理: 36800_20250213.zip
已提取并重命名为: 36800_20250213.xbrl

处理: 51010_20250328.zip
已提取并重命名为: 51010_20250328.xbrl

处理: 78140_20250328.zip
已提取并重命名为: 78140_20250328.xbrl

处理: 96720_20250327.zip
已提取并重命名为: 96720_20250327.xbrl

处理: 97220_20250327.zip
已提取并重命名为: 97220_20250327.xbrl

处理: 40600_20250326.zip
已提取并重命名为: 40600_20250326.xbrl

处理: 94490_20250324.zip
已提取并重命名为: 94490_20250324.xbrl

处理: 23730_20250130.zip
已提取并重命名为: 23730_20250130.xbrl

处理: 93860_20250328.zip
已提取并重命名为: 93860_20250328.xbrl

处理: 39680_20250327.zip
已提取并重命名为: 39680_20250327.xbrl

处理: 48960_20250328.zip
已提取并重命名为: 48960_20250328.xbrl

处理: 73530_20250326.zip
已提取并重命名为: 73530_20250326.xbrl

处理: 78060_20250327.zip
已提取并重命名为: 78060_20250327.xbrl

处理: 26950_20250130.zip
已提取并重命名为: 26950_20250130.xbrl

处理: 45870_20250328.zip
已提取并重命名为: 45870_20250328.xbrl

处理: 98720_20250220.zip
已提取并重命名为: 98720_20250220.xbrl

处理: 64640_20250326.zip
已提取并重命名为: 64640_20250326.xbrl

处理: 60260_20250319.zip
已提取并重命名为: 60260_20250319.xbrl

处理: 31860_20250221.zip
已提取并重命名为: 31860_20250221.xbrl

处理: 64650_20250328.zip
已提取并重命名为: 64650_20250328.xbrl

处理: 48120_20250328.zip
已提取并重命名为: 48120_20250328.xbrl

处理: 24920_20250328.zip
已提取并重命名为: 24920_20250328.xbrl

处理: 30910_20250326.zip
已提取并重命名为: 30910_20250326.xbrl

处理: 70800_20250328.zip
已提取并重命名为: 70800_20250328.xbrl

处理: 45760_20250326.zip
已提取并重命名为: 45760_20250326.xbrl

处理: 25330_20250324.zip
已提取并重命名为: 25330_20250324.xbrl

处理: 66400_20250217.zip
已提取并重命名为: 66400_20250217.xbrl

处理: 42480_20250326.zip
已提取并重命名为: 42480_20250326.xbrl

处理: 73780_20250129.zip
已提取并重命名为: 73780_20250129.xbrl

处理: 262A0_20250328.zip
已提取并重命名为: 262A0_20250328.xbrl

处理: 46420_20250328.zip
已提取并重命名为: 46420_20250328.xbrl

处理: 24710_20250303.zip
已提取并重命名为: 24710_20250303.xbrl

处理: 77900_20250328.zip
已提取并重命名为: 77900_20250328.xbrl

处理: 14290_20250328.zip
已提取并重命名为: 14290_20250328.xbrl

处理: 33770_20250227.zip
已提取并重命名为: 33770_20250227.xbrl

处理: 96470_20250228.zip
已提取并重命名为: 96470_20250228.xbrl

处理: 44520_20250324.zip
已提取并重命名为: 44520_20250324.xbrl

处理: 37500_20250210.zip
已提取并重命名为: 37500_20250210.xbrl

处理: 59420_20250228.zip
已提取并重命名为: 59420_20250228.xbrl


In [2]:
import xml.etree.ElementTree as ET
from bs4 import BeautifulSoup
import html
import pandas as pd
import logging
from datetime import datetime
import os

# 设置路径
xbrl_dir = "/Users/wenjun/Downloads/JPXData/AGM/XBRL"
tables_dir = "/Users/wenjun/Downloads/JPXData/AGM/XBRL/Tables"
log_dir = "/Users/wenjun/Downloads/JPXData/AGM/Logs"

# 确保输出目录和日志目录存在
os.makedirs(tables_dir, exist_ok=True)
os.makedirs(log_dir, exist_ok=True)

# 设置日志
log_file = os.path.join(log_dir, f"agm_analysis_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log")
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(log_file, encoding='utf-8'),
        logging.StreamHandler()
    ]
)

def find_resolution_elements(root, namespaces):
    """查找所有可能的决议相关元素"""
    resolution_keywords = [
        'resolution', 'meeting', 'shareholder', '決議', '議決', '株主', '総会',
        '議案', '議事', '採決', '投票', '賛成', '反対', '可決', '否決'
    ]
    
    found_elements = []
    for elem in root.iter():
        if '}' in elem.tag:
            element_name = elem.tag.split('}')[1].lower()
            if any(keyword in element_name for keyword in resolution_keywords):
                found_elements.append(elem.tag)
                logging.debug(f"找到决议相关元素: {element_name}")
    
    return found_elements

def html_table_to_dataframe(table):
    """将HTML表格转换为DataFrame"""
    rows = []
    for tr in table.find_all('tr'):
        row = [td.get_text(strip=True) for td in tr.find_all(['td', 'th'])]
        if row:  # 只添加非空行
            rows.append(row)
    
    if not rows:
        return None
    
    # 使用第一行作为列名
    headers = rows[0]
    data = rows[1:]
    
    # 确保所有行的列数一致
    max_cols = max(len(row) for row in data)
    if len(headers) < max_cols:
        # 如果表头列数不足，添加额外的列名
        headers.extend([f'Column_{i+1}' for i in range(len(headers), max_cols)])
    
    # 确保所有数据行的列数一致
    for row in data:
        if len(row) < max_cols:
            row.extend([''] * (max_cols - len(row)))
    
    df = pd.DataFrame(data, columns=headers)
    return df

def process_xbrl_file(file_path):
    """处理单个XBRL文件并提取表格"""
    try:
        tree = ET.parse(file_path)
        root = tree.getroot()
        base_name = os.path.splitext(os.path.basename(file_path))[0]
        
        logging.info(f"处理文件: {base_name}")
        
        resolution_elements = find_resolution_elements(root, {})
        if not resolution_elements:
            logging.warning(f"在文件 {file_path} 中未找到决议相关元素")
            return None
        
        logging.info(f"找到 {len(resolution_elements)} 个可能的决议相关元素")
        
        for elem_path in resolution_elements:
            elements = root.findall(f'.//{elem_path}')
            for i, element in enumerate(elements, 1):
                if element.text and element.text.strip():
                    text = html.unescape(element.text)
                    logging.debug(f"处理元素内容: {text[:200]}...")
                    
                    # 尝试解析HTML
                    soup = BeautifulSoup(text, 'html.parser')
                    tables = soup.find_all('table')
                    
                    if tables:
                        for j, table in enumerate(tables, 1):
                            df = html_table_to_dataframe(table)
                            if df is not None:
                                # 保存原始表格
                                output_file = os.path.join(tables_dir, f"{base_name}.csv")
                                df.to_csv(output_file, index=False, encoding='utf-8-sig')
                                logging.debug(f"已保存表格到: {output_file}")
        
        return True
    
    except Exception as e:
        logging.error(f"处理文件 {file_path} 时出错: {str(e)}", exc_info=True)
        return None

def main(n=None):
    """
    主程序
    Args:
        n (int, optional): 要处理的文件数量，None表示处理所有文件
    """
    xbrl_files = [f for f in os.listdir(xbrl_dir) if f.endswith('.xbrl')]
    
    # 如果指定了n，则只处理前n个文件
    if n is not None:
        n = min(n, len(xbrl_files))  # 确保n不超过文件总数
        xbrl_files = xbrl_files[:n]
        logging.info(f"将处理前 {n} 个XBRL文件（共 {len(xbrl_files)} 个文件）")
    else:
        logging.info(f"将处理所有 {len(xbrl_files)} 个XBRL文件")

    for i, file_name in enumerate(xbrl_files, 1):
        logging.info(f"处理第 {i}/{len(xbrl_files)} 个文件: {file_name}")
        file_path = os.path.join(xbrl_dir, file_name)
        
        # 处理文件内容
        process_xbrl_file(file_path)

if __name__ == "__main__":
    # 可以在这里指定要处理的文件数量
    
    #n = 5  # 比如处理前5个文件，设置为None则处理所有文件
    main()

2025-04-01 00:14:57,994 - INFO - 将处理所有 505 个XBRL文件
2025-04-01 00:14:57,995 - INFO - 处理第 1/505 个文件: 74220_20250318.xbrl
2025-04-01 00:14:57,998 - INFO - 处理文件: 74220_20250318
2025-04-01 00:14:57,999 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,016 - INFO - 处理第 2/505 个文件: 48830_20250328.xbrl
2025-04-01 00:14:58,017 - INFO - 处理文件: 48830_20250328
2025-04-01 00:14:58,018 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,030 - INFO - 处理第 3/505 个文件: 48960_20250328.xbrl
2025-04-01 00:14:58,031 - INFO - 处理文件: 48960_20250328
2025-04-01 00:14:58,032 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,035 - INFO - 处理第 4/505 个文件: 43940_20250303.xbrl
2025-04-01 00:14:58,037 - INFO - 处理文件: 43940_20250303
2025-04-01 00:14:58,037 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,045 - INFO - 处理第 5/505 个文件: 36230_20250326.xbrl
2025-04-01 00:14:58,047 - INFO - 处理文件: 36230_20250326
2025-04-01 00:14:58,047 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,055 - INFO - 处理第 6/505 个文件: 78270_20250131.xbrl
2025-04-01 00:14:58,057 - INFO - 处理文件: 78270_20250131
2025-04-01 00:14:58,058 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,066 - INFO - 处理第 7/505 个文件: 73600_20250226.xbrl
2025-04-01 00:14:58,067 - INFO - 处理文件: 73600_20250226
2025-04-01 00:14:58,068 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,073 - INFO - 处理第 8/505 个文件: 21240_20250328.xbrl
2025-04-01 00:14:58,075 - INFO - 处理文件: 21240_20250328
2025-04-01 00:14:58,076 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,082 - INFO - 处理第 9/505 个文件: 260A0_20250327.xbrl
2025-04-01 00:14:58,084 - INFO - 处理文件: 260A0_20250327
2025-04-01 00:14:58,084 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,130 - INFO - 处理第 10/505 个文件: 44520_20250324.xbrl
2025-04-01 00:14:58,132 - INFO - 处理文件: 44520_20250324
2025-04-01 00:14:58,133 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,142 - INFO - 处理第 11/505 个文件: 73880_20250305.xbrl
2025-04-01 00:14:58,143 - INFO - 处理文件: 73880_20250305
2025-04-01 00:14:58,143 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,148 - INFO - 处理第 12/505 个文件: 39400_20250327.xbrl
2025-04-01 00:14:58,149 - INFO - 处理文件: 39400_20250327
2025-04-01 00:14:58,149 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,154 - INFO - 处理第 13/505 个文件: 92790_20250203.xbrl
2025-04-01 00:14:58,155 - INFO - 处理文件: 92790_20250203
2025-04-01 00:14:58,155 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,160 - INFO - 处理第 14/505 个文件: 33500_20250326.xbrl
2025-04-01 00:14:58,160 - INFO - 处理文件: 33500_20250326
2025-04-01 00:14:58,161 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,164 - INFO - 处理第 15/505 个文件: 58190_20250324.xbrl
2025-04-01 00:14:58,165 - INFO - 处理文件: 58190_20250324
2025-04-01 00:14:58,165 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,168 - INFO - 处理第 16/505 个文件: 36330_20250321.xbrl
2025-04-01 00:14:58,169 - INFO - 处理文件: 36330_20250321
2025-04-01 00:14:58,169 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,172 - INFO - 处理第 17/505 个文件: 36950_20250319.xbrl
2025-04-01 00:14:58,173 - INFO - 处理文件: 36950_20250319
2025-04-01 00:14:58,173 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,178 - INFO - 处理第 18/505 个文件: 55890_20250327.xbrl
2025-04-01 00:14:58,179 - INFO - 处理文件: 55890_20250327
2025-04-01 00:14:58,179 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,182 - INFO - 处理第 19/505 个文件: 60710_20250327.xbrl
2025-04-01 00:14:58,183 - INFO - 处理文件: 60710_20250327
2025-04-01 00:14:58,183 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,186 - INFO - 处理第 20/505 个文件: 79850_20250304.xbrl
2025-04-01 00:14:58,187 - INFO - 处理文件: 79850_20250304
2025-04-01 00:14:58,187 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,189 - INFO - 处理第 21/505 个文件: 55630_20250327.xbrl
2025-04-01 00:14:58,189 - INFO - 处理文件: 55630_20250327
2025-04-01 00:14:58,190 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,193 - INFO - 处理第 22/505 个文件: 49950_20250304.xbrl
2025-04-01 00:14:58,194 - INFO - 处理文件: 49950_20250304
2025-04-01 00:14:58,194 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,197 - INFO - 处理第 23/505 个文件: 51260_20250325.xbrl
2025-04-01 00:14:58,197 - INFO - 处理文件: 51260_20250325
2025-04-01 00:14:58,197 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,201 - INFO - 处理第 24/505 个文件: 145A0_20250327.xbrl
2025-04-01 00:14:58,201 - INFO - 处理文件: 145A0_20250327
2025-04-01 00:14:58,202 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,205 - INFO - 处理第 25/505 个文件: 45640_20250218.xbrl
2025-04-01 00:14:58,205 - INFO - 处理文件: 45640_20250218
2025-04-01 00:14:58,206 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,207 - INFO - 处理第 26/505 个文件: 78790_20250304.xbrl
2025-04-01 00:14:58,208 - INFO - 处理文件: 78790_20250304
2025-04-01 00:14:58,208 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,211 - INFO - 处理第 27/505 个文件: 68580_20250326.xbrl
2025-04-01 00:14:58,212 - INFO - 处理文件: 68580_20250326
2025-04-01 00:14:58,212 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,215 - INFO - 处理第 28/505 个文件: 43870_20250226.xbrl
2025-04-01 00:14:58,216 - INFO - 处理文件: 43870_20250226
2025-04-01 00:14:58,216 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,217 - INFO - 处理第 29/505 个文件: 64640_20250326.xbrl
2025-04-01 00:14:58,218 - INFO - 处理文件: 64640_20250326
2025-04-01 00:14:58,218 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,221 - INFO - 处理第 30/505 个文件: 298A0_20250327.xbrl
2025-04-01 00:14:58,222 - INFO - 处理文件: 298A0_20250327
2025-04-01 00:14:58,222 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,226 - INFO - 处理第 31/505 个文件: 45790_20250326.xbrl
2025-04-01 00:14:58,226 - INFO - 处理文件: 45790_20250326
2025-04-01 00:14:58,227 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,230 - INFO - 处理第 32/505 个文件: 39940_20250227.xbrl
2025-04-01 00:14:58,231 - INFO - 处理文件: 39940_20250227
2025-04-01 00:14:58,231 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,235 - INFO - 处理第 33/505 个文件: 32480_20250130.xbrl
2025-04-01 00:14:58,236 - INFO - 处理文件: 32480_20250130
2025-04-01 00:14:58,236 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,239 - INFO - 处理第 34/505 个文件: 72270_20250228.xbrl
2025-04-01 00:14:58,239 - INFO - 处理文件: 72270_20250228
2025-04-01 00:14:58,240 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,245 - INFO - 处理第 35/505 个文件: 80600_20250328.xbrl
2025-04-01 00:14:58,245 - INFO - 处理文件: 80600_20250328
2025-04-01 00:14:58,246 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,254 - INFO - 处理第 36/505 个文件: 45760_20250326.xbrl
2025-04-01 00:14:58,255 - INFO - 处理文件: 45760_20250326
2025-04-01 00:14:58,255 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,258 - INFO - 处理第 37/505 个文件: 60290_20250328.xbrl
2025-04-01 00:14:58,259 - INFO - 处理文件: 60290_20250328
2025-04-01 00:14:58,259 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,262 - INFO - 处理第 38/505 个文件: 30730_20250228.xbrl
2025-04-01 00:14:58,263 - INFO - 处理文件: 30730_20250228
2025-04-01 00:14:58,263 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,265 - INFO - 处理第 39/505 个文件: 290A0_20250326.xbrl
2025-04-01 00:14:58,265 - INFO - 处理文件: 290A0_20250326
2025-04-01 00:14:58,266 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,267 - INFO - 处理第 40/505 个文件: 40530_20250328.xbrl
2025-04-01 00:14:58,268 - INFO - 处理文件: 40530_20250328
2025-04-01 00:14:58,268 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,271 - INFO - 处理第 41/505 个文件: 39470_20250327.xbrl
2025-04-01 00:14:58,271 - INFO - 处理文件: 39470_20250327
2025-04-01 00:14:58,272 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,280 - INFO - 处理第 42/505 个文件: 41870_20250306.xbrl
2025-04-01 00:14:58,280 - INFO - 处理文件: 41870_20250306
2025-04-01 00:14:58,281 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,283 - INFO - 处理第 43/505 个文件: 212A0_20250131.xbrl
2025-04-01 00:14:58,284 - INFO - 处理文件: 212A0_20250131
2025-04-01 00:14:58,284 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,287 - INFO - 处理第 44/505 个文件: 97310_20250328.xbrl
2025-04-01 00:14:58,288 - INFO - 处理文件: 97310_20250328
2025-04-01 00:14:58,288 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,292 - INFO - 处理第 45/505 个文件: 50390_20250328.xbrl
2025-04-01 00:14:58,292 - INFO - 处理文件: 50390_20250328
2025-04-01 00:14:58,293 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,295 - INFO - 处理第 46/505 个文件: 24890_20250327.xbrl
2025-04-01 00:14:58,296 - INFO - 处理文件: 24890_20250327
2025-04-01 00:14:58,296 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,300 - INFO - 处理第 47/505 个文件: 65580_20250227.xbrl
2025-04-01 00:14:58,300 - INFO - 处理文件: 65580_20250227
2025-04-01 00:14:58,301 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,304 - INFO - 处理第 48/505 个文件: 30640_20250327.xbrl
2025-04-01 00:14:58,304 - INFO - 处理文件: 30640_20250327
2025-04-01 00:14:58,305 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,308 - INFO - 处理第 49/505 个文件: 46120_20250328.xbrl
2025-04-01 00:14:58,309 - INFO - 处理文件: 46120_20250328
2025-04-01 00:14:58,309 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,313 - INFO - 处理第 50/505 个文件: 75010_20250228.xbrl
2025-04-01 00:14:58,313 - INFO - 处理文件: 75010_20250228
2025-04-01 00:14:58,313 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,334 - INFO - 处理第 51/505 个文件: 94410_20250327.xbrl
2025-04-01 00:14:58,336 - INFO - 处理文件: 94410_20250327
2025-04-01 00:14:58,336 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,340 - INFO - 处理第 52/505 个文件: 89140_20250327.xbrl
2025-04-01 00:14:58,341 - INFO - 处理文件: 89140_20250327
2025-04-01 00:14:58,342 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,347 - INFO - 处理第 53/505 个文件: 62690_20250328.xbrl
2025-04-01 00:14:58,347 - INFO - 处理文件: 62690_20250328
2025-04-01 00:14:58,348 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,351 - INFO - 处理第 54/505 个文件: 39070_20250227.xbrl
2025-04-01 00:14:58,351 - INFO - 处理文件: 39070_20250227
2025-04-01 00:14:58,352 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,354 - INFO - 处理第 55/505 个文件: 58680_20250328.xbrl
2025-04-01 00:14:58,354 - INFO - 处理文件: 58680_20250328
2025-04-01 00:14:58,355 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,359 - INFO - 处理第 56/505 个文件: 68380_20250204.xbrl
2025-04-01 00:14:58,360 - INFO - 处理文件: 68380_20250204
2025-04-01 00:14:58,360 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,365 - INFO - 处理第 57/505 个文件: 21690_20250327.xbrl
2025-04-01 00:14:58,365 - INFO - 处理文件: 21690_20250327
2025-04-01 00:14:58,366 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,368 - INFO - 处理第 58/505 个文件: 94460_20250106.xbrl
2025-04-01 00:14:58,369 - INFO - 处理文件: 94460_20250106
2025-04-01 00:14:58,369 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,374 - INFO - 处理第 59/505 个文件: 49270_20250327.xbrl
2025-04-01 00:14:58,374 - INFO - 处理文件: 49270_20250327
2025-04-01 00:14:58,374 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,378 - INFO - 处理第 60/505 个文件: 39830_20250328.xbrl
2025-04-01 00:14:58,378 - INFO - 处理文件: 39830_20250328
2025-04-01 00:14:58,378 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,381 - INFO - 处理第 61/505 个文件: 65600_20250326.xbrl
2025-04-01 00:14:58,381 - INFO - 处理文件: 65600_20250326
2025-04-01 00:14:58,381 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,385 - INFO - 处理第 62/505 个文件: 55420_20250328.xbrl
2025-04-01 00:14:58,386 - INFO - 处理文件: 55420_20250328
2025-04-01 00:14:58,386 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,389 - INFO - 处理第 63/505 个文件: 27880_20250328.xbrl
2025-04-01 00:14:58,390 - INFO - 处理文件: 27880_20250328
2025-04-01 00:14:58,390 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,395 - INFO - 处理第 64/505 个文件: 33460_20250225.xbrl
2025-04-01 00:14:58,395 - INFO - 处理文件: 33460_20250225
2025-04-01 00:14:58,396 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,398 - INFO - 处理第 65/505 个文件: 14490_20250328.xbrl
2025-04-01 00:14:58,399 - INFO - 处理文件: 14490_20250328
2025-04-01 00:14:58,399 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,401 - INFO - 处理第 66/505 个文件: 93840_20250327.xbrl
2025-04-01 00:14:58,402 - INFO - 处理文件: 93840_20250327
2025-04-01 00:14:58,402 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,406 - INFO - 处理第 67/505 个文件: 65460_20250328.xbrl
2025-04-01 00:14:58,407 - INFO - 处理文件: 65460_20250328
2025-04-01 00:14:58,407 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,411 - INFO - 处理第 68/505 个文件: 42510_20250326.xbrl
2025-04-01 00:14:58,412 - INFO - 处理文件: 42510_20250326
2025-04-01 00:14:58,412 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,417 - INFO - 处理第 69/505 个文件: 42210_20250327.xbrl
2025-04-01 00:14:58,418 - INFO - 处理文件: 42210_20250327
2025-04-01 00:14:58,418 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,422 - INFO - 处理第 70/505 个文件: 98370_20250305.xbrl
2025-04-01 00:14:58,423 - INFO - 处理文件: 98370_20250305
2025-04-01 00:14:58,423 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,426 - INFO - 处理第 71/505 个文件: 95430_20250327.xbrl
2025-04-01 00:14:58,427 - INFO - 处理文件: 95430_20250327
2025-04-01 00:14:58,427 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,431 - INFO - 处理第 72/505 个文件: 93390_20250328.xbrl
2025-04-01 00:14:58,432 - INFO - 处理文件: 93390_20250328
2025-04-01 00:14:58,432 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,436 - INFO - 处理第 73/505 个文件: 334A0_20250328.xbrl
2025-04-01 00:14:58,437 - INFO - 处理文件: 334A0_20250328
2025-04-01 00:14:58,437 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,440 - INFO - 处理第 74/505 个文件: 70930_20250327.xbrl
2025-04-01 00:14:58,440 - INFO - 处理文件: 70930_20250327
2025-04-01 00:14:58,441 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,444 - INFO - 处理第 75/505 个文件: 25970_20250326.xbrl
2025-04-01 00:14:58,444 - INFO - 处理文件: 25970_20250326
2025-04-01 00:14:58,445 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,448 - INFO - 处理第 76/505 个文件: 73780_20250129.xbrl
2025-04-01 00:14:58,449 - INFO - 处理文件: 73780_20250129
2025-04-01 00:14:58,449 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,451 - INFO - 处理第 77/505 个文件: 73140_20250328.xbrl
2025-04-01 00:14:58,451 - INFO - 处理文件: 73140_20250328
2025-04-01 00:14:58,452 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,454 - INFO - 处理第 78/505 个文件: 43750_20250328.xbrl
2025-04-01 00:14:58,455 - INFO - 处理文件: 43750_20250328
2025-04-01 00:14:58,455 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,458 - INFO - 处理第 79/505 个文件: 47220_20250326.xbrl
2025-04-01 00:14:58,459 - INFO - 处理文件: 47220_20250326
2025-04-01 00:14:58,459 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,464 - INFO - 处理第 80/505 个文件: 41970_20250228.xbrl
2025-04-01 00:14:58,464 - INFO - 处理文件: 41970_20250228
2025-04-01 00:14:58,465 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,468 - INFO - 处理第 81/505 个文件: 73090_20250328.xbrl
2025-04-01 00:14:58,468 - INFO - 处理文件: 73090_20250328
2025-04-01 00:14:58,469 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,472 - INFO - 处理第 82/505 个文件: 18970_20250328.xbrl
2025-04-01 00:14:58,473 - INFO - 处理文件: 18970_20250328
2025-04-01 00:14:58,473 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,476 - INFO - 处理第 83/505 个文件: 71720_20250327.xbrl
2025-04-01 00:14:58,477 - INFO - 处理文件: 71720_20250327
2025-04-01 00:14:58,477 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,479 - INFO - 处理第 84/505 个文件: 187A0_20250110.xbrl
2025-04-01 00:14:58,480 - INFO - 处理文件: 187A0_20250110
2025-04-01 00:14:58,480 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,483 - INFO - 处理第 85/505 个文件: 39040_20250328.xbrl
2025-04-01 00:14:58,483 - INFO - 处理文件: 39040_20250328
2025-04-01 00:14:58,484 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,488 - INFO - 处理第 86/505 个文件: 44040_20250327.xbrl
2025-04-01 00:14:58,489 - INFO - 处理文件: 44040_20250327
2025-04-01 00:14:58,490 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,494 - INFO - 处理第 87/505 个文件: 40600_20250326.xbrl
2025-04-01 00:14:58,495 - INFO - 处理文件: 40600_20250326
2025-04-01 00:14:58,495 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,497 - INFO - 处理第 88/505 个文件: 66630_20250319.xbrl
2025-04-01 00:14:58,498 - INFO - 处理文件: 66630_20250319
2025-04-01 00:14:58,498 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,500 - INFO - 处理第 89/505 个文件: 95650_20250129.xbrl
2025-04-01 00:14:58,501 - INFO - 处理文件: 95650_20250129
2025-04-01 00:14:58,501 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,504 - INFO - 处理第 90/505 个文件: 60870_20250106.xbrl
2025-04-01 00:14:58,505 - INFO - 处理文件: 60870_20250106
2025-04-01 00:14:58,505 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,528 - INFO - 处理第 91/505 个文件: 70630_20250106.xbrl
2025-04-01 00:14:58,529 - INFO - 处理文件: 70630_20250106
2025-04-01 00:14:58,529 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,533 - INFO - 处理第 92/505 个文件: 262A0_20250328.xbrl
2025-04-01 00:14:58,534 - INFO - 处理文件: 262A0_20250328
2025-04-01 00:14:58,535 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,540 - INFO - 处理第 93/505 个文件: 68710_20250328.xbrl
2025-04-01 00:14:58,541 - INFO - 处理文件: 68710_20250328
2025-04-01 00:14:58,541 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,545 - INFO - 处理第 94/505 个文件: 50380_20250328.xbrl
2025-04-01 00:14:58,546 - INFO - 处理文件: 50380_20250328
2025-04-01 00:14:58,546 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,548 - INFO - 处理第 95/505 个文件: 37880_20250324.xbrl
2025-04-01 00:14:58,548 - INFO - 处理文件: 37880_20250324
2025-04-01 00:14:58,549 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,552 - INFO - 处理第 96/505 个文件: 64740_20250228.xbrl
2025-04-01 00:14:58,553 - INFO - 处理文件: 64740_20250228
2025-04-01 00:14:58,553 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,557 - INFO - 处理第 97/505 个文件: 58670_20250325.xbrl
2025-04-01 00:14:58,558 - INFO - 处理文件: 58670_20250325
2025-04-01 00:14:58,558 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,562 - INFO - 处理第 98/505 个文件: 70330_20250328.xbrl
2025-04-01 00:14:58,563 - INFO - 处理文件: 70330_20250328
2025-04-01 00:14:58,563 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,566 - INFO - 处理第 99/505 个文件: 94250_20250131.xbrl
2025-04-01 00:14:58,566 - INFO - 处理文件: 94250_20250131
2025-04-01 00:14:58,566 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,570 - INFO - 处理第 100/505 个文件: 36530_20250131.xbrl
2025-04-01 00:14:58,571 - INFO - 处理文件: 36530_20250131
2025-04-01 00:14:58,571 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,575 - INFO - 处理第 101/505 个文件: 78140_20250328.xbrl
2025-04-01 00:14:58,576 - INFO - 处理文件: 78140_20250328
2025-04-01 00:14:58,576 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,579 - INFO - 处理第 102/505 个文件: 99720_20250228.xbrl
2025-04-01 00:14:58,580 - INFO - 处理文件: 99720_20250228
2025-04-01 00:14:58,580 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,585 - INFO - 处理第 103/505 个文件: 52460_20250228.xbrl
2025-04-01 00:14:58,585 - INFO - 处理文件: 52460_20250228
2025-04-01 00:14:58,586 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,588 - INFO - 处理第 104/505 个文件: 27000_20250328.xbrl
2025-04-01 00:14:58,589 - INFO - 处理文件: 27000_20250328
2025-04-01 00:14:58,589 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,593 - INFO - 处理第 105/505 个文件: 43720_20250328.xbrl
2025-04-01 00:14:58,594 - INFO - 处理文件: 43720_20250328
2025-04-01 00:14:58,594 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,598 - INFO - 处理第 106/505 个文件: 61800_20250321.xbrl
2025-04-01 00:14:58,599 - INFO - 处理文件: 61800_20250321
2025-04-01 00:14:58,599 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,605 - INFO - 处理第 107/505 个文件: 70740_20250228.xbrl
2025-04-01 00:14:58,606 - INFO - 处理文件: 70740_20250228
2025-04-01 00:14:58,606 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,629 - INFO - 处理第 108/505 个文件: 43610_20250221.xbrl
2025-04-01 00:14:58,629 - INFO - 处理文件: 43610_20250221
2025-04-01 00:14:58,630 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,632 - INFO - 处理第 109/505 个文件: 44380_20250328.xbrl
2025-04-01 00:14:58,633 - INFO - 处理文件: 44380_20250328
2025-04-01 00:14:58,633 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,636 - INFO - 处理第 110/505 个文件: 40130_20250321.xbrl
2025-04-01 00:14:58,637 - INFO - 处理文件: 40130_20250321
2025-04-01 00:14:58,637 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,643 - INFO - 处理第 111/505 个文件: 42640_20250328.xbrl
2025-04-01 00:14:58,643 - INFO - 处理文件: 42640_20250328
2025-04-01 00:14:58,643 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,648 - INFO - 处理第 112/505 个文件: 92150_20250306.xbrl
2025-04-01 00:14:58,648 - INFO - 处理文件: 92150_20250306
2025-04-01 00:14:58,649 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,652 - INFO - 处理第 113/505 个文件: 41920_20250327.xbrl
2025-04-01 00:14:58,653 - INFO - 处理文件: 41920_20250327
2025-04-01 00:14:58,653 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,656 - INFO - 处理第 114/505 个文件: 48110_20250328.xbrl
2025-04-01 00:14:58,657 - INFO - 处理文件: 48110_20250328
2025-04-01 00:14:58,657 - INFO - 找到 1 个可能的决议相关元素
2025-04-01 00:14:58,659 - ERROR - 处理文件 /Users/wenjun/Downloads/JPXData/AGM/XBRL/48110_20250328.xbrl 时出错: max() arg is an empty sequence
Traceback (most recent call last):
  File "/var/folders/bb/04y0ymcd2jz23qgx3f1q9n7c0000gn/T/ipykernel_4196/662794452.py", line 104, in process_xbrl_file
    df = html_table_to_dataframe(table)

In [49]:
import os
import xml.etree.ElementTree as ET
from bs4 import BeautifulSoup
import html
import re
import pandas as pd
from collections import defaultdict
from datetime import datetime
import logging

# 在notebook开头添加
import logging

# 配置日志只输出到终端
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

# 测试日志是否正常工作
logging.info("日志系统初始化完成")

def clean_table_data(df):
    """清理表格数据"""
    # 打印列名，用于调试
    logging.info(f"原始列名: {df.columns.tolist()}")
    
    # 处理可决要件和结果混在一起的情况
    result_columns = [col for col in df.columns if '決議' in col or '可決' in col]
    if result_columns:
        # 创建新的列
        df['決議の結果'] = ''
        df['賛成割合（％）'] = ''
        
        # 分离结果和百分比
        for idx, row in df.iterrows():
            result_text = str(row[result_columns[0]])
            
            # 处理可决/否决结果
            if '可決' in result_text:
                df.at[idx, '決議の結果'] = '可決'
            elif '否決' in result_text:
                df.at[idx, '決議の結果'] = '否決'
            
            # 提取百分比 - 使用更灵活的正则表达式
            percent_match = re.search(r'(\d+\.?\d*)%', result_text)
            if percent_match:
                df.at[idx, '賛成割合（％）'] = percent_match.group(1)
            else:
                # 尝试其他格式的百分比
                alt_match = re.search(r'(\d+\.?\d*)％', result_text)
                if alt_match:
                    df.at[idx, '賛成割合（％）'] = alt_match.group(1)
                else:
                    # 尝试从賛成数（個）和反対数（個）计算
                    agree_cols = [col for col in df.columns if '賛成' in col]
                    oppose_cols = [col for col in df.columns if '反対' in col]
                    if agree_cols and oppose_cols:
                        try:
                            agree = float(str(row[agree_cols[0]]).replace(',', ''))
                            oppose = float(str(row[oppose_cols[0]]).replace(',', ''))
                            if agree + oppose > 0:
                                rate = (agree / (agree + oppose)) * 100
                                df.at[idx, '賛成割合（％）'] = f"{rate:.2f}"
                        except:
                            pass
    
    # 处理数据挤在一起的情况
    for col in df.columns:
        if df[col].dtype == 'object':
            # 尝试分割挤在一起的数据
            df[col] = df[col].apply(lambda x: x.split('19,')[0] if isinstance(x, str) and '19,' in x else x)
    
    # 删除空的Column_7列
    if 'Column_7' in df.columns and df['Column_7'].isna().all():
        df = df.drop('Column_7', axis=1)
    
    # 重新排列列顺序
    desired_columns = [
        '決議事項', '賛成数（個）', '反対数（個）', '棄権数（個）', 
        '可決要件', '決議の結果', '賛成割合（％）'
    ]
    
    # 只保留存在的列
    existing_columns = [col for col in desired_columns if col in df.columns]
    df = df[existing_columns]
    
    return df

def html_table_to_dataframe(table):
    """将HTML表格转换为DataFrame"""
    rows = []
    for tr in table.find_all('tr'):
        row = [td.get_text(strip=True) for td in tr.find_all(['td', 'th'])]
        if row:  # 只添加非空行
            rows.append(row)
    
    if not rows:
        return None
    
    # 使用第一行作为列名
    headers = rows[0]
    data = rows[1:]
    
    # 确保所有行的列数一致
    max_cols = max(len(row) for row in data)
    if len(headers) < max_cols:
        # 如果表头列数不足，添加额外的列名
        headers.extend([f'Column_{i+1}' for i in range(len(headers), max_cols)])
    
    # 确保所有数据行的列数一致
    for row in data:
        if len(row) < max_cols:
            row.extend([''] * (max_cols - len(row)))
    
    df = pd.DataFrame(data, columns=headers)
    
    # 清理数据
    df = clean_table_data(df)
    
    return df

def extract_approval_rate(df):
    """提取最低赞成率"""
    if '賛成割合（％）' not in df.columns:
        logging.info("未找到賛成割合（％）列")
        return None
    
    rates = []
    for idx, rate in df['賛成割合（％）'].items():
        if pd.notna(rate) and rate != '':
            try:
                # 移除百分号并转换为浮点数
                rate_value = float(str(rate).replace('%', '').replace('％', ''))
                rates.append(rate_value)
                logging.info(f"找到赞成率: {rate_value}% (行 {idx+1})")
            except Exception as e:
                logging.warning(f"无法解析赞成率 '{rate}' (行 {idx+1}): {str(e)}")
                continue
    
    if rates:
        min_rate = min(rates)
        logging.info(f"最低赞成率: {min_rate}%")
        return min_rate
    else:
        logging.info("未找到有效的赞成率")
        return None

def process_xbrl_file(file_path):
    """处理单个XBRL文件"""
    try:
        # 解析XML文件
        tree = ET.parse(file_path)
        root = tree.getroot()
        
        # 获取文件名（不含扩展名）用于输出文件
        base_name = os.path.splitext(os.path.basename(file_path))[0]
        
        # 尝试获取公司名称
        company_name = None
        for elem in root.iter():
            if '}' in elem.tag:
                element_name = elem.tag.split('}')[1].lower()
                if 'company' in element_name or 'name' in element_name or '会社' in element_name:
                    if elem.text and elem.text.strip():
                        company_name = elem.text.strip()
                        logging.info(f"找到公司名称: {company_name}")
                        break
        
        # 查找所有可能的决议相关元素
        resolution_elements = find_resolution_elements(root, {})
        
        if not resolution_elements:
            logging.info(f"文件 {base_name} 中未找到决议相关元素")
            return None
        
        logging.info(f"处理文件: {base_name} (公司: {company_name if company_name else '未知'})")
        
        # 处理每个找到的元素
        for elem_path in resolution_elements:
            elements = root.findall(f'.//{elem_path}')
            logging.info(f"找到 {len(elements)} 个决议元素")
            
            for i, element in enumerate(elements, 1):
                if element.text and element.text.strip():
                    text = html.unescape(element.text)
                    
                    # 尝试解析HTML
                    soup = BeautifulSoup(text, 'html.parser')
                    tables = soup.find_all('table')
                    
                    if tables:
                        logging.info(f"在决议元素 {i} 中找到 {len(tables)} 个表格")
                        
                        for j, table in enumerate(tables, 1):
                            # 转换为DataFrame
                            df = html_table_to_dataframe(table)
                            if df is not None:
                                logging.info(f"处理表格 {j} 的列: {df.columns.tolist()}")
                                
                                # 提取最低赞成率
                                min_rate = extract_approval_rate(df)
                                
                                # 检查是否有否决的决议
                                rejection_flag = 'N'
                                if '決議の結果' in df.columns:
                                    rejection_flag = 'Y' if df['決議の結果'].str.contains('否決', na=False).any() else 'N'
                                    logging.info(f"决议结果: {'有否决' if rejection_flag == 'Y' else '全部通过'}")
                                else:
                                    # 尝试在其他列中查找否决信息
                                    for col in df.columns:
                                        if df[col].astype(str).str.contains('否決', na=False).any():
                                            rejection_flag = 'Y'
                                            logging.info(f"在列 {col} 中发现否决")
                                            break
                                
                                return {
                                    'file_name': f"{base_name}",
                                    'company_name': company_name if company_name else 'N/A',
                                    'min_approval_rate': min_rate if min_rate is not None else 'N/A',
                                    'rejection_flag': rejection_flag
                                }
    
    except Exception as e:
        logging.error(f"处理文件 {file_path} 时出错: {str(e)}", exc_info=True)
    
    return None

def find_resolution_elements(root, namespaces):
    """查找所有可能的决议相关元素"""
    resolution_keywords = [
        'resolution', 'meeting', 'shareholder', '決議', '議決', '株主', '総会'
    ]
    
    found_elements = []
    for elem in root.iter():
        if '}' in elem.tag:
            element_name = elem.tag.split('}')[1].lower()
            if any(keyword in element_name for keyword in resolution_keywords):
                found_elements.append(elem.tag)
    
    return found_elements

def process_all_files(n=None):
    """处理所有文件并生成汇总报告"""
    # 设置路径
    xbrl_dir = "/Users/wenjun/Downloads/JPXData/AGM/XBRL"
    output_dir = "/Users/wenjun/Downloads/Quants/EDINET"
    
    # 确保输出目录存在
    os.makedirs(output_dir, exist_ok=True)
    
    results = []
    xbrl_files = [f for f in os.listdir(xbrl_dir) if f.endswith('.xbrl')]
    
    #print(len(xbrl_files))
    # 如果指定了n，则只处理前n个文件
    if n is not None:
        n = min(n, len(xbrl_files))
        xbrl_files = xbrl_files[:n]
        logging.info(f"将处理前 {n} 个文件（共有 {len(xbrl_files)} 个XBRL文件）")
    else:
        logging.info(f"将处理所有 {len(xbrl_files)} 个XBRL文件")
    
    for i, file_name in enumerate(xbrl_files, 1):
        file_path = os.path.join(xbrl_dir, file_name)
        logging.info(f"[{i}/{len(xbrl_files)}] 正在处理文件: {file_path}")
        result = process_xbrl_file(file_path)
        if result:
            results.append(result)
    
    # 创建结果DataFrame
    df_results = pd.DataFrame(results)
    
    # 保存结果
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    output_file = os.path.join(output_dir, f'analysis_results_{timestamp}_n{len(results)}.csv')
    df_results.to_csv(output_file, index=False, encoding='utf-8-sig')
    
    return df_results

if __name__ == "__main__":
    results_df = process_all_files()
    print(f"处理完成，共分析 {len(results_df)} 个文件")
    print("\n结果预览：")
    print(results_df)

2025-04-01 01:42:36,374 - INFO - 日志系统初始化完成
2025-04-01 01:42:36,383 - INFO - 将处理所有 505 个XBRL文件
2025-04-01 01:42:36,384 - INFO - [1/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/74220_20250318.xbrl
2025-04-01 01:42:36,389 - INFO - 找到公司名称: 東邦レマック株式会社
2025-04-01 01:42:36,392 - INFO - 处理文件: 74220_20250318 (公司: 東邦レマック株式会社)
2025-04-01 01:42:36,396 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,402 - INFO - 在决议元素 1 中找到 2 个表格
2025-04-01 01:42:36,403 - INFO - 原始列名: ['決議事項', '', '賛成数(個)', '反対数(個)', '棄権数(個)', '可決要件', '決議の結果及び賛成(反対)割合(％)', 'Column_8']
2025-04-01 01:42:36,405 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,405 - INFO - 找到赞成率: 99.95% (行 1)
2025-04-01 01:42:36,405 - INFO - 找到赞成率: 99.95% (行 2)
2025-04-01 01:42:36,406 - INFO - 找到赞成率: 99.87% (行 3)
2025-04-01 01:42:36,406 - INFO - 找到赞成率: 99.95% (行 4)
2025-04-01 01:42:36,406 - INFO - 找到赞成率: 99.92% (行 5)
2025-04-01 01:42:36,407 - INFO - 找到赞成率: 99.87% (行 6)
2025-04-01 01:42:36,407 - INFO - 找到赞成率: 99.85% (行 7)
2025-04-01 01:42:36,407 - INFO - 找到赞成率: 99.85% (行 8)
2025-04-01 01:42:36,407 - INFO - 最低赞成率: 99.85%
2025-04-01 01:42:36,408 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,408 - INFO - [2/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/48830_20250328.xbrl
2025-04-01 01:42:36,409 - INFO - 找到公司名称: 株式会社モダリス
2025-04-01 01:42:36,409 - INFO - 处理文件: 48830_20250328 (公司: 株式会社モダリス)
2025-04-01 01:42:36,409 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,413 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,416 - INFO - 原始列名: ['決議事項', '賛成数(個)', '反対数(個)', '棄権数(個)', '可決要件', '決議の結果及び賛成(反対)割合(％)', 'Column_7']
2025-04-01 01:42:36,419 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,420 - INFO - 找到赞成率: 92.9% (行 1)
2025-04-01 01:42:36,421 - INFO - 找到赞成率: 90.94% (行 2)
2025-04-01 01:42:36,421 - INFO - 找到赞成率: 93.45% (行 4)
2025-04-01 01:42:36,422 - INFO - 找到赞成率: 93.17% (行 5)
2025-04-01 01:42:36,422 - INFO - 找到赞成率: 93.18% (行 6)
2025-04-01 01:42:36,423 - INFO - 找到赞成率: 94.19% (行 8)
2025-04-01 01:42:36,424 - INFO - 找到赞成率: 94.69% (行 9)
2025-04-01 01:42:36,424 - INFO - 找到赞成率: 88.46% (行 10)
2025-04-01 01:42:36,424 - INFO - 最低赞成率: 88.46%
2025-04-01 01:42:36,425 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,425 - INFO - [3/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/48960_20250328.xbrl
2025-04-01 01:42:36,426 - INFO - 找到公司名称: 株式会社ケイファーマ
2025-04-01 01:42:36,426 - INFO - 处理文件: 48960_20250328 (公司: 株式会社ケイファーマ)
2025-04-01 01:42:36,427 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,428 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,429 - INFO - 原始列名: ['決議事項', '賛成数(個)', '反対数(個)', '棄権数(個)', '可決要件', '決議の結果及び賛成(反対)割合(％)', 'Column_7']
2025-04-01 01:42:36,430 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,431 - INFO - 找到赞成率: 99.86% (行 1)
2025-04-01 01:42:36,431 - INFO - 找到赞成率: 100.0% (行 3)
2025-04-01 01:42:36,431 - INFO - 最低赞成率: 99.86%
2025-04-01 01:42:36,431 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,432 - INFO - [4/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/43940_20250303.xbrl
2025-04-01 01:42:36,432 - INFO - 找到公司名称: 株式会社エクスモーション
2025-04-01 01:42:36,433 - INFO - 处理文件: 43940_20250303 (公司: 株式会社エクスモーション)
2025-04-01 01:42:36,433 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,437 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,438 - INFO - 原始列名: ['決議事項', '賛成数(個)', '反対数(個)', '棄権数(個)', '可決要件', '決議の結果及び賛成(反対)割合(％)', 'Column_7']
2025-04-01 01:42:36,439 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,440 - INFO - 找到赞成率: 99.87% (行 1)
2025-04-01 01:42:36,440 - INFO - 找到赞成率: 99.58% (行 3)
2025-04-01 01:42:36,440 - INFO - 找到赞成率: 99.56% (行 4)
2025-04-01 01:42:36,441 - INFO - 找到赞成率: 99.62% (行 5)
2025-04-01 01:42:36,441 - INFO - 找到赞成率: 99.62% (行 6)
2025-04-01 01:42:36,441 - INFO - 找到赞成率: 99.62% (行 7)
2025-04-01 01:42:36,442 - INFO - 找到赞成率: 99.62% (行 8)
2025-04-01 01:42:36,442 - INFO - 找到赞成率: 99.64% (行 10)
2025-04-01 01:42:36,442 - INFO - 找到赞成率: 99.66% (行 11)
2025-04-01 01:42:36,442 - INFO - 最低赞成率: 99.56%
2025-04-01 01:42:36,443 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,443 - INFO - [5/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/36230_20250326.xbrl
2025-04-01 01:42:36,444 - INFO - 找到公司名称: ビリングシステム株式会社
2025-04-01 01:42:36,444 - INFO - 处理文件: 36230_20250326 (公司: ビリングシステム株式会社)
2025-04-01 01:42:36,444 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,447 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,448 - INFO - 原始列名: ['決議事項', '賛成数(個)', '反対数(個)', '棄権数(個)', '可決要件', '決議の結果及び（賛成の割合）', 'Column_7']
2025-04-01 01:42:36,449 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,450 - INFO - 找到赞成率: 99.21% (行 1)
2025-04-01 01:42:36,450 - INFO - 找到赞成率: 96.41% (行 3)
2025-04-01 01:42:36,450 - INFO - 找到赞成率: 98.81% (行 4)
2025-04-01 01:42:36,451 - INFO - 找到赞成率: 98.91% (行 5)
2025-04-01 01:42:36,451 - INFO - 找到赞成率: 98.92% (行 6)
2025-04-01 01:42:36,451 - INFO - 找到赞成率: 98.7% (行 7)
2025-04-01 01:42:36,452 - INFO - 找到赞成率: 98.74% (行 8)
2025-04-01 01:42:36,452 - INFO - 找到赞成率: 98.98% (行 9)
2025-04-01 01:42:36,452 - INFO - 找到赞成率: 98.99% (行 10)
2025-04-01 01:42:36,453 - INFO - 最低赞成率: 96.41%
2025-04-01 01:42:36,453 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,453 - INFO - [6/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/78270_20250131.xbrl
2025-04-01 01:42:36,454 - INFO - 找到公司名称: 株式会社オービス
2025-04-01 01:42:36,454 - INFO - 处理文件: 78270_20250131 (公司: 株式会社オービス)
2025-04-01 01:42:36,454 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,457 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,457 - INFO - 原始列名: ['決議事項', '賛成（個）', '反対（個）', '棄権（個）', '可決要件', '決議の結果及び賛成割合（％）']
2025-04-01 01:42:36,459 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,459 - INFO - 找到赞成率: 99.73% (行 1)
2025-04-01 01:42:36,459 - INFO - 找到赞成率: 99.45% (行 3)
2025-04-01 01:42:36,460 - INFO - 找到赞成率: 99.36% (行 4)
2025-04-01 01:42:36,460 - INFO - 找到赞成率: 99.29% (行 5)
2025-04-01 01:42:36,460 - INFO - 找到赞成率: 99.34% (行 6)
2025-04-01 01:42:36,460 - INFO - 找到赞成率: 99.28% (行 7)
2025-04-01 01:42:36,461 - INFO - 找到赞成率: 99.33% (行 8)
2025-04-01 01:42:36,461 - INFO - 找到赞成率: 99.28% (行 9)
2025-04-01 01:42:36,461 - INFO - 找到赞成率: 99.36% (行 10)
2025-04-01 01:42:36,461 - INFO - 最低赞成率: 99.28%
2025-04-01 01:42:36,462 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,462 - INFO - [7/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/73600_20250226.xbrl
2025-04-01 01:42:36,463 - INFO - 找到公司名称: 株式会社オンデック
2025-04-01 01:42:36,463 - INFO - 处理文件: 73600_20250226 (公司: 株式会社オンデック)
2025-04-01 01:42:36,463 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,465 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,465 - INFO - 原始列名: ['決議事項', '賛成数(個)', '反対数(個)', '棄権数(個)', '可決要件', '決議の結果及び賛成(反対)割合(％)', 'Column_7']
2025-04-01 01:42:36,467 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,467 - INFO - 找到赞成率: 99.8% (行 2)
2025-04-01 01:42:36,467 - INFO - 找到赞成率: 99.78% (行 3)
2025-04-01 01:42:36,468 - INFO - 最低赞成率: 99.78%
2025-04-01 01:42:36,468 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,468 - INFO - [8/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/21240_20250328.xbrl
2025-04-01 01:42:36,469 - INFO - 找到公司名称: 株式会社ジェイ エイ シー リクルートメント
2025-04-01 01:42:36,469 - INFO - 处理文件: 21240_20250328 (公司: 株式会社ジェイ エイ シー リクルートメント)
2025-04-01 01:42:36,469 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,472 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,473 - INFO - 原始列名: ['決議事項', '賛成数(個)', '反対数(個)', '棄権数(個)', '可決要件', '決議の結果及び賛成割合(％)', 'Column_7']
2025-04-01 01:42:36,474 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,475 - INFO - 找到赞成率: 99.89% (行 1)
2025-04-01 01:42:36,475 - INFO - 找到赞成率: 98.9% (行 3)
2025-04-01 01:42:36,475 - INFO - 找到赞成率: 99.75% (行 4)
2025-04-01 01:42:36,476 - INFO - 找到赞成率: 99.76% (行 5)
2025-04-01 01:42:36,476 - INFO - 找到赞成率: 99.74% (行 6)
2025-04-01 01:42:36,476 - INFO - 找到赞成率: 99.75% (行 7)
2025-04-01 01:42:36,476 - INFO - 找到赞成率: 99.77% (行 8)
2025-04-01 01:42:36,476 - INFO - 找到赞成率: 99.78% (行 9)
2025-04-01 01:42:36,477 - INFO - 找到赞成率: 99.75% (行 10)
2025-04-01 01:42:36,477 - INFO - 找到赞成率: 99.83% (行 11)
2025-04-01 01:42:36,477 - INFO - 找到赞成率: 97.81% (行 12)
2025-04-01 01:42:36,477 - INFO - 找到赞成率: 99.85% (行 14)
2025-04-01 01:42:36,478 - INFO - 最低赞成率: 97.81%
2025-04-01 01:42:36,478 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,478 - INFO - [9/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/260A0_20250327.xbrl
2025-04-01 01:42:36,479 - INFO - 找到公司名称: 株式会社オルツ
2025-04-01 01:42:36,479 - INFO - 处理文件: 260A0_20250327 (公司: 株式会社オルツ)
2025-04-01 01:42:36,480 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,482 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,483 - INFO - 原始列名: ['決議事項', '賛成数(個)', '反対数(個)', '棄権数(個)', '可決要件', '決議の結果及び賛成(反対)割合(％)', 'Column_7']
2025-04-01 01:42:36,486 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,486 - INFO - 找到赞成率: 96.46% (行 1)
2025-04-01 01:42:36,486 - INFO - 找到赞成率: 94.78% (行 2)
2025-04-01 01:42:36,487 - INFO - 找到赞成率: 94.63% (行 4)
2025-04-01 01:42:36,487 - INFO - 找到赞成率: 94.57% (行 5)
2025-04-01 01:42:36,487 - INFO - 找到赞成率: 94.6% (行 6)
2025-04-01 01:42:36,488 - INFO - 找到赞成率: 89.24% (行 7)
2025-04-01 01:42:36,488 - INFO - 找到赞成率: 89.68% (行 8)
2025-04-01 01:42:36,488 - INFO - 最低赞成率: 89.24%
2025-04-01 01:42:36,489 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,489 - INFO - [10/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/44520_20250324.xbrl
2025-04-01 01:42:36,490 - INFO - 找到公司名称: 花王株式会社
2025-04-01 01:42:36,490 - INFO - 处理文件: 44520_20250324 (公司: 花王株式会社)
2025-04-01 01:42:36,490 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,496 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,497 - INFO - 原始列名: ['決議事項', '賛成(個)', '反対(個)', '棄権(個)', '可決要件', '決議の結果(賛成の割合)', 'Column_7']
2025-04-01 01:42:36,499 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,499 - INFO - 找到赞成率: 94.26% (行 1)
2025-04-01 01:42:36,500 - INFO - 找到赞成率: 90.32% (行 3)
2025-04-01 01:42:36,500 - INFO - 找到赞成率: 90.5% (行 4)
2025-04-01 01:42:36,500 - INFO - 找到赞成率: 91.53% (行 5)
2025-04-01 01:42:36,500 - INFO - 找到赞成率: 91.19% (行 6)
2025-04-01 01:42:36,501 - INFO - 找到赞成率: 92.16% (行 7)
2025-04-01 01:42:36,501 - INFO - 找到赞成率: 92.21% (行 8)
2025-04-01 01:42:36,501 - INFO - 找到赞成率: 92.25% (行 9)
2025-04-01 01:42:36,501 - INFO - 找到赞成率: 87.57% (行 10)
2025-04-01 01:42:36,502 - INFO - 找到赞成率: 93.85% (行 11)
2025-04-01 01:42:36,502 - INFO - 找到赞成率: 91.69% (行 13)
2025-04-01 01:42:36,502 - INFO - 找到赞成率: 94.15% (行 14)
2025-04-01 01:42:36,503 - INFO - 找到赞成率: 27.52% (行 16)
2025-04-01 01:42:36,503 - INFO - 找到赞成率: 24.28% (行 17)
2025-04-01 01:42:36,503 - INFO - 找到赞成率: 18.05% (行 18)
2025-04-01 01:42:36,503 - INFO - 找到赞成率: 11.32% (行 19)
2025-04-01 01:42:36,504 - INFO - 找到赞成率: 23.67% (行 20)
2025-04-01 01:42:36,504 - INFO - 找到赞成率: 29.13% (行 21)
2025-04-01 01:42:36,504 - INFO - 找到赞成率: 29.37% (行 22)
2025-04-01 01:42:36,504 - INFO - 找到赞成率: 24.41% (行 23)
2025-04-01 01:42:36,505 - INFO - 最低赞成率: 11.32%
2025-04-01 01:42:36,505 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,505 - INFO - [11/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/73880_20250305.xbrl
2025-04-01 01:42:36,506 - INFO - 找到公司名称: 株式会社ＦＰパートナー
2025-04-01 01:42:36,506 - INFO - 处理文件: 73880_20250305 (公司: 株式会社ＦＰパートナー)
2025-04-01 01:42:36,506 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,510 - INFO - 在决议元素 1 中找到 2 个表格
2025-04-01 01:42:36,511 - INFO - 原始列名: ['決議事項', '賛成数(個)', '反対数(個)', '棄権数(個)', '可決要件', '決議の結果及び賛成(反対)割合(％)', 'Column_7']
2025-04-01 01:42:36,512 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,512 - INFO - 找到赞成率: 92.17% (行 2)
2025-04-01 01:42:36,513 - INFO - 找到赞成率: 97.11% (行 3)
2025-04-01 01:42:36,513 - INFO - 找到赞成率: 97.1% (行 4)
2025-04-01 01:42:36,513 - INFO - 找到赞成率: 97.1% (行 5)
2025-04-01 01:42:36,513 - INFO - 找到赞成率: 97.11% (行 6)
2025-04-01 01:42:36,514 - INFO - 找到赞成率: 97.08% (行 7)
2025-04-01 01:42:36,514 - INFO - 找到赞成率: 97.05% (行 8)
2025-04-01 01:42:36,514 - INFO - 找到赞成率: 97.05% (行 9)
2025-04-01 01:42:36,514 - INFO - 找到赞成率: 97.11% (行 10)
2025-04-01 01:42:36,515 - INFO - 找到赞成率: 96.66% (行 11)
2025-04-01 01:42:36,515 - INFO - 最低赞成率: 92.17%
2025-04-01 01:42:36,515 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,516 - INFO - [12/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/39400_20250327.xbrl
2025-04-01 01:42:36,517 - INFO - 找到公司名称: 株式会社ノムラシステムコーポレーション
2025-04-01 01:42:36,517 - INFO - 处理文件: 39400_20250327 (公司: 株式会社ノムラシステムコーポレーション)
2025-04-01 01:42:36,517 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,521 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,522 - INFO - 原始列名: ['決議事項', '賛成数(個)', '反対数(個)', '棄権数(個)', '可決要件', '決議の結果及び賛成割合(％)', 'Column_7']
2025-04-01 01:42:36,528 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,529 - INFO - 找到赞成率: 99.59% (行 1)
2025-04-01 01:42:36,529 - INFO - 找到赞成率: 99.05% (行 3)
2025-04-01 01:42:36,530 - INFO - 找到赞成率: 99.23% (行 4)
2025-04-01 01:42:36,530 - INFO - 找到赞成率: 99.23% (行 5)
2025-04-01 01:42:36,531 - INFO - 找到赞成率: 99.28% (行 6)
2025-04-01 01:42:36,531 - INFO - 找到赞成率: 99.32% (行 7)
2025-04-01 01:42:36,531 - INFO - 找到赞成率: 99.39% (行 8)
2025-04-01 01:42:36,531 - INFO - 找到赞成率: 99.39% (行 9)
2025-04-01 01:42:36,532 - INFO - 找到赞成率: 99.22% (行 10)
2025-04-01 01:42:36,532 - INFO - 找到赞成率: 99.25% (行 12)
2025-04-01 01:42:36,532 - INFO - 找到赞成率: 99.27% (行 13)
2025-04-01 01:42:36,532 - INFO - 找到赞成率: 99.31% (行 14)
2025-04-01 01:42:36,533 - INFO - 最低赞成率: 99.05%
2025-04-01 01:42:36,534 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,534 - INFO - [13/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/92790_20250203.xbrl
2025-04-01 01:42:36,535 - INFO - 找到公司名称: 株式会社ギフトホールディングス
2025-04-01 01:42:36,535 - INFO - 处理文件: 92790_20250203 (公司: 株式会社ギフトホールディングス)
2025-04-01 01:42:36,535 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,565 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,566 - INFO - 原始列名: ['決議事項', '賛成（個）', '反対（個）', '棄権（個）', '可決要件', '決議の結果及び賛成割合（％）']
2025-04-01 01:42:36,567 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,568 - INFO - 找到赞成率: 99.81% (行 1)
2025-04-01 01:42:36,568 - INFO - 找到赞成率: 91.91% (行 3)
2025-04-01 01:42:36,568 - INFO - 找到赞成率: 95.77% (行 4)
2025-04-01 01:42:36,569 - INFO - 找到赞成率: 95.77% (行 5)
2025-04-01 01:42:36,569 - INFO - 找到赞成率: 95.76% (行 6)
2025-04-01 01:42:36,569 - INFO - 找到赞成率: 95.77% (行 7)
2025-04-01 01:42:36,570 - INFO - 找到赞成率: 95.77% (行 8)
2025-04-01 01:42:36,570 - INFO - 找到赞成率: 99.76% (行 9)
2025-04-01 01:42:36,570 - INFO - 找到赞成率: 95.64% (行 11)
2025-04-01 01:42:36,570 - INFO - 找到赞成率: 99.75% (行 12)
2025-04-01 01:42:36,571 - INFO - 找到赞成率: 99.73% (行 13)
2025-04-01 01:42:36,571 - INFO - 最低赞成率: 91.91%
2025-04-01 01:42:36,571 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,571 - INFO - [14/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/33500_20250326.xbrl
2025-04-01 01:42:36,572 - INFO - 找到公司名称: 株式会社メタプラネット
2025-04-01 01:42:36,572 - INFO - 处理文件: 33500_20250326 (公司: 株式会社メタプラネット)
2025-04-01 01:42:36,573 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,575 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,576 - INFO - 原始列名: ['決議事項', '賛成（個）', '反対（個）', '棄権（個）', '可決要件', '決議の結果及び賛成割合（％）']
2025-04-01 01:42:36,577 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,577 - INFO - 找到赞成率: 86.48% (行 2)
2025-04-01 01:42:36,578 - INFO - 找到赞成率: 90.22% (行 3)
2025-04-01 01:42:36,578 - INFO - 找到赞成率: 90.24% (行 4)
2025-04-01 01:42:36,578 - INFO - 找到赞成率: 90.22% (行 5)
2025-04-01 01:42:36,579 - INFO - 找到赞成率: 90.25% (行 6)
2025-04-01 01:42:36,579 - INFO - 找到赞成率: 90.23% (行 7)
2025-04-01 01:42:36,579 - INFO - 找到赞成率: 90.23% (行 8)
2025-04-01 01:42:36,580 - INFO - 找到赞成率: 86.48% (行 9)
2025-04-01 01:42:36,580 - INFO - 找到赞成率: 90.23% (行 10)
2025-04-01 01:42:36,580 - INFO - 找到赞成率: 86.15% (行 11)
2025-04-01 01:42:36,580 - INFO - 最低赞成率: 86.15%
2025-04-01 01:42:36,581 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,581 - INFO - [15/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/58190_20250324.xbrl
2025-04-01 01:42:36,582 - INFO - 找到公司名称: カナレ電気株式会社
2025-04-01 01:42:36,582 - INFO - 处理文件: 58190_20250324 (公司: カナレ電気株式会社)
2025-04-01 01:42:36,582 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,584 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,585 - INFO - 原始列名: ['決議事項', '賛成（個）', '反対（個）', '棄権（個）', '可決要件', '決議の結果及び賛成割合（％）']
2025-04-01 01:42:36,586 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,586 - INFO - 找到赞成率: 98.61% (行 1)
2025-04-01 01:42:36,587 - INFO - 找到赞成率: 98.52% (行 3)
2025-04-01 01:42:36,587 - INFO - 找到赞成率: 98.33% (行 5)
2025-04-01 01:42:36,587 - INFO - 找到赞成率: 97.06% (行 6)
2025-04-01 01:42:36,587 - INFO - 最低赞成率: 97.06%
2025-04-01 01:42:36,588 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,588 - INFO - [16/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/36330_20250321.xbrl
2025-04-01 01:42:36,589 - INFO - 找到公司名称: GMOペパボ株式会社
2025-04-01 01:42:36,589 - INFO - 处理文件: 36330_20250321 (公司: GMOペパボ株式会社)
2025-04-01 01:42:36,589 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,591 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,592 - INFO - 原始列名: ['決議事項', '賛成数(個)', '反対数(個)', '棄権数(個)', '可決要件', '決議の結果及び賛成(反対)割合(％)', 'Column_7']
2025-04-01 01:42:36,594 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,594 - INFO - 找到赞成率: 99.31% (行 1)
2025-04-01 01:42:36,594 - INFO - 找到赞成率: 91.26% (行 3)
2025-04-01 01:42:36,594 - INFO - 找到赞成率: 93.91% (行 4)
2025-04-01 01:42:36,595 - INFO - 找到赞成率: 96.78% (行 5)
2025-04-01 01:42:36,595 - INFO - 找到赞成率: 96.83% (行 6)
2025-04-01 01:42:36,595 - INFO - 找到赞成率: 96.84% (行 7)
2025-04-01 01:42:36,595 - INFO - 找到赞成率: 96.84% (行 8)
2025-04-01 01:42:36,596 - INFO - 最低赞成率: 91.26%
2025-04-01 01:42:36,596 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,596 - INFO - [17/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/36950_20250319.xbrl
2025-04-01 01:42:36,597 - INFO - 找到公司名称: ＧＭＯリサーチ＆ＡＩ株式会社
2025-04-01 01:42:36,597 - INFO - 处理文件: 36950_20250319 (公司: ＧＭＯリサーチ＆ＡＩ株式会社)
2025-04-01 01:42:36,597 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,602 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,603 - INFO - 原始列名: ['決議事項', '賛成数(個)', '反対数(個)', '棄権数(個)', '可決要件', '決議の結果及び賛成(反対)割合(％)', 'Column_7']
2025-04-01 01:42:36,604 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,605 - INFO - 找到赞成率: 99.78% (行 1)
2025-04-01 01:42:36,605 - INFO - 找到赞成率: 99.64% (行 2)
2025-04-01 01:42:36,605 - INFO - 找到赞成率: 99.68% (行 3)
2025-04-01 01:42:36,606 - INFO - 找到赞成率: 98.38% (行 5)
2025-04-01 01:42:36,606 - INFO - 找到赞成率: 99.49% (行 6)
2025-04-01 01:42:36,606 - INFO - 找到赞成率: 98.38% (行 7)
2025-04-01 01:42:36,606 - INFO - 找到赞成率: 99.49% (行 8)
2025-04-01 01:42:36,606 - INFO - 找到赞成率: 99.48% (行 9)
2025-04-01 01:42:36,607 - INFO - 找到赞成率: 99.49% (行 10)
2025-04-01 01:42:36,607 - INFO - 找到赞成率: 99.49% (行 11)
2025-04-01 01:42:36,607 - INFO - 找到赞成率: 99.49% (行 12)
2025-04-01 01:42:36,608 - INFO - 找到赞成率: 99.53% (行 14)
2025-04-01 01:42:36,608 - INFO - 最低赞成率: 98.38%
2025-04-01 01:42:36,608 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,609 - INFO - [18/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/55890_20250327.xbrl
2025-04-01 01:42:36,609 - INFO - 找到公司名称: 株式会社オートサーバー
2025-04-01 01:42:36,610 - INFO - 处理文件: 55890_20250327 (公司: 株式会社オートサーバー)
2025-04-01 01:42:36,610 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,612 - INFO - 在决议元素 1 中找到 1 个表格
2025-04-01 01:42:36,613 - INFO - 原始列名: ['決議事項', '賛成数(個)', '反対数(個)', '棄権数(個)', '可決要件', '決議の結果及び賛成割合(％)', 'Column_7']
2025-04-01 01:42:36,614 - INFO - 处理表格 1 的列: ['決議事項', '可決要件', '決議の結果', '賛成割合（％）']
2025-04-01 01:42:36,615 - INFO - 找到赞成率: 99.9% (行 1)
2025-04-01 01:42:36,615 - INFO - 找到赞成率: 99.89% (行 2)
2025-04-01 01:42:36,615 - INFO - 找到赞成率: 100.0% (行 4)
2025-04-01 01:42:36,616 - INFO - 找到赞成率: 99.53% (行 5)
2025-04-01 01:42:36,616 - INFO - 找到赞成率: 99.61% (行 6)
2025-04-01 01:42:36,616 - INFO - 最低赞成率: 99.53%
2025-04-01 01:42:36,617 - INFO - 决议结果: 全部通过
2025-04-01 01:42:36,617 - INFO - [19/505] 正在处理文件: /Users/wenjun/Downloads/JPXData/AGM/XBRL/60710_20250327.xbrl
2025-04-01 01:42:36,617 - INFO - 找到公司名称: 株式会社ＩＢＪ
2025-04-01 01:42:36,618 - INFO - 处理文件: 60710_20250327 (公司: 株式会社ＩＢＪ)
2025-04-01 01:42:36,618 - INFO - 找到 1 个决议元素
2025-04-01 01:42:36,621 - INFO - 在决议元素 1 中找到 1 个表格

处理完成，共分析 502 个文件

结果预览：
          file_name       company_name min_approval_rate rejection_flag
0    74220_20250318         東邦レマック株式会社             99.85              N
1    48830_20250328           株式会社モダリス             88.46              N
2    48960_20250328         株式会社ケイファーマ             99.86              N
3    43940_20250303       株式会社エクスモーション             99.56              N
4    36230_20250326       ビリングシステム株式会社             96.41              N
..              ...                ...               ...            ...
497  49710_20250326            メック株式会社             94.19              N
498  36490_20250328       株式会社ファインデックス             85.26              N
499  43740_20250327  株式会社ＲＯＢＯＴ　ＰＡＹＭＥＮＴ             99.77              N
500  47460_20250328           株式会社東計電算             92.32              N
501  40190_20250328           株式会社スタメン             99.64              N

[502 rows x 4 columns]

In [6]:
df2 = pd.read_csv('/Users/wenjun/Downloads/Quants/EDINET/data_2025-03-31.csv')
df2['secCode'] = df2['secCode'].astype(str).apply(lambda x: x.split('.')[0] if '.' in x else x)


# 确保数据类型正确
df2['docTypeCode'] = df2['docTypeCode'].astype(str)
df2['ordinanceCode'] = df2['ordinanceCode'].astype(str)
df2['formCode'] = df2['formCode'].astype(str)

# 修改后的筛选条件
filtered_df2 = df2[
    (df2['docTypeCode'].str.strip() == '180.0') & 
    (df2['ordinanceCode'].str.strip() == '10.0') & 
    (df2['formCode'].str.strip() == '053000') &
    (df2['secCode'].notna()) &
    (df2['currentReportReason'] == '第19条第2項第9号の2') &
    (df2['submitDateTime'] >= '2025-01-01')
]

/var/folders/bb/04y0ymcd2jz23qgx3f1q9n7c0000gn/T/ipykernel_4196/1423714968.py:1: DtypeWarning: Columns (3,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('/Users/wenjun/Downloads/Quants/EDINET/data_2025-03-31.csv')

In [24]:
df = results_df
df[['ticker', 'submission_date']] = df['file_name'].str.split('_', expand=True)
df

          file_name min_approval_rate rejection_flag ticker submission_date
0    74220_20250318             99.85              N  74220        20250318
1    48830_20250328             88.46              N  48830        20250328
2    48960_20250328             99.86              N  48960        20250328
3    43940_20250303             99.56              N  43940        20250303
4    36230_20250326             96.41              N  36230        20250326
..              ...               ...            ...    ...             ...
497  49710_20250326             94.19              N  49710        20250326
498  36490_20250328             85.26              N  36490        20250328
499  43740_20250327             99.77              N  43740        20250327
500  47460_20250328             92.32              N  47460        20250328
501  40190_20250328             99.64              N  40190        20250328

[502 rows x 5 columns]

In [25]:
filtered_df2

,seqNumber,docID,edinetCode,secCode,JCN,filerName,fundCode,ordinanceCode,formCode,docTypeCode,...,docInfoEditStatus,disclosureStatus,xbrlFlag,pdfFlag,attachDocFlag,englishDocFlag,csvFlag,legalStatus,date,submission_date
452140,95,S100V1DZ,E05181,94460,4.180001e+12,株式会社サカイホールディングス,NaN,10,053000,180,...,0,0,1,1,0,0,1,1,2025-01-06,20250106
452169,124,S100V12A,E27043,60870,8.011001e+12,株式会社アビスト,NaN,10,053000,180,...,0,0,1,1,0,0,1,1,2025-01-06,20250106
452171,126,S100V1FM,E34748,70630,8.010001e+12,株式会社Ｂｉｒｄｍａｎ,NaN,10,053000,180,...,0,0,1,1,0,0,1,1,2025-01-06,20250106
452361,73,S100V1Q3,E30648,60940,2.010401e+12,株式会社フリークアウト・ホールディングス,NaN,10,053000,180,...,0,0,1,1,0,0,1,1,2025-01-07,20250107
452801,127,S100V27X,E02762,99410,5.010001e+12,太洋物産株式会社,NaN,10,053000,180,...,0,0,1,1,0,0,1,1,2025-01-09,20250109
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
468906,947,S100VIQM,E36708,40740,4.010401e+12,株式会社ラキール,NaN,10,053000,180,...,0,0,1,1,0,0,1,1,2025-03-28,20250328
468909,950,S100VIV9,E37160,42580,8.010001e+12,株式会社網屋,NaN,10,053000,180,...,0,0,1,1,0,0,1,1,2025-03-28,20250328
468916,957,S100VITB,E37466,50270,7.010401e+12,ＡｎｙＭｉｎｄ Ｇｒｏｕｐ株式会社,NaN,10,053000,180,...,0,0,1,1,0,0,1,1,2025-03-28,20250328
468927,968,S100VIFT,E02404,79560,8.010001e+12,ピジョン株式会社,NaN,10,053000,180,...,0,0,1,1,0,0,1,1,2025-03-28,20250328
468928,969,S100VINP,E27276,36710,8.340001e+12,ソフトマックス株式会社,NaN,10,053000,180,...,0,0,1,1,0,0,1,1,2025-03-28,20250328

In [26]:
# 确保filtered_df2中的secCode是字符串类型
filtered_df2['secCode'] = filtered_df2['secCode'].astype(str)

# 确保df中的ticker是字符串类型
df['ticker'] = df['ticker'].astype(str)

# 修改合并代码
result_df = pd.merge(
    df,
    filtered_df2[['secCode', 'filerName', 'docID', 'submission_date']],
    left_on=['ticker', 'submission_date'],
    right_on=['secCode', 'submission_date'],
    how='left'
)

# 整理最终列
final_df = result_df[[
    'ticker', 
    'filerName', 
    'min_approval_rate', 
    'rejection_flag',
    'submission_date',
    'docID'
]]

/var/folders/bb/04y0ymcd2jz23qgx3f1q9n7c0000gn/T/ipykernel_4196/691993704.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df2['secCode'] = filtered_df2['secCode'].astype(str)

In [27]:
final_df

,ticker,filerName,min_approval_rate,rejection_flag,submission_date,docID
0,74220,東邦レマック株式会社,99.85,N,20250318,S100VF1Y
1,48830,株式会社モダリス,88.46,N,20250328,S100VISH
2,48960,株式会社ケイファーマ,99.86,N,20250328,S100VIBE
3,43940,株式会社エクスモーション,99.56,N,20250303,S100VBWQ
4,36230,ビリングシステム株式会社,96.41,N,20250326,S100VH40
...,...,...,...,...,...,...
497,49710,メック株式会社,94.19,N,20250326,S100VGQ1
498,36490,株式会社ファインデックス,85.26,N,20250328,S100VI1W
499,43740,株式会社ＲＯＢＯＴ ＰＡＹＭＥＮＴ,99.77,N,20250327,S100VHKT
500,47460,株式会社東計電算,92.32,N,20250328,S100VIAC
501,40190,株式会社スタメン,99.64,N,20250328,S100VIBU

In [28]:
import yfinance as yf
from tqdm import tqdm
# 获取市值数据
print("正在获取市值数据...")
final_df['market_cap'] = None  # 创建新列存储市值数据

def get_market_cap(code):
    try:
        # 将企业代码转换为yfinance格式（4位数字 + .T）
        # 首先确保是字符串格式，然后取前4位，补零，最后加上.T
        ticker = f"{str(code)[:4].zfill(4)}.T"
        stock = yf.Ticker(ticker)
        mcap = stock.info.get('marketCap', None)
        return mcap
    except:
        return None
# 使用tqdm添加进度条
for idx in tqdm(final_df.index):
    code = final_df.loc[idx, 'ticker']
    mcap = get_market_cap(code)
    final_df.loc[idx, 'market_cap'] = mcap

# 将市值转换为十亿日元单位
final_df['market_cap_billions'] = final_df['market_cap'] / 1_000_000_000

# 显示结果预览
print("\n数据预览：")
print(final_df[['ticker', 'market_cap_billions']].head())

# 显示数据获取成功率
total = len(final_df)
success = final_df['market_cap'].notna().sum()
print(f"\n数据获取成功率: {success}/{total} ({success/total*100:.1f}%)")
final_df = final_df.drop(columns=['market_cap'])
final_df['market_cap_billions'] = final_df['market_cap_billions'].round(1)

/var/folders/bb/04y0ymcd2jz23qgx3f1q9n7c0000gn/T/ipykernel_4196/1468847494.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['market_cap'] = None  # 创建新列存储市值数据

正在获取市值数据...

  4%|▍         | 21/502 [00:10<03:51,  2.08it/s]2025-04-01 00:37:26,513 - ERROR - 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/4995.T?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=4995.T&crumb=UqZSGYGx%2F5h
  7%|▋         | 33/502 [00:18<03:54,  2.00it/s]2025-04-01 00:37:33,273 - ERROR - 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/7227.T?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=7227.T&crumb=UqZSGYGx%2F5h
  9%|▉         | 44/502 [00:24<03:47,  2.01it/s]2025-04-01 00:37:39,892 - ERROR - 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/5039.T?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=5039.T&crumb=UqZSGYGx%2F5h
 13%|█▎        | 63/502 [00:34<03:34,  2.04it/s]2025-04-01 00:37:50,491 - ERROR - 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/3346.T?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=3346.T&crumb=UqZSGYGx%2F5h
 13%|█▎        | 64/502 [00:36<06:05,  1.20it/s]2025-04-01 00:37:51,837 - ERROR - 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/1449.T?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=1449.T&crumb=UqZSGYGx%2F5h
 25%|██▍       | 123/502 [01:06<03:05,  2.04it/s]2025-04-01 00:38:22,089 - ERROR - 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/3066.T?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=3066.T&crumb=UqZSGYGx%2F5h
 45%|████▌     | 226/502 [01:58<02:19,  1.98it/s]2025-04-01 00:39:13,953 - ERROR - 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/3419.T?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=3419.T&crumb=UqZSGYGx%2F5h
 72%|███████▏  | 363/502 [03:07<01:07,  2.07it/s]2025-04-01 00:40:23,627 - ERROR - 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/6076.T?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=6076.T&crumb=UqZSGYGx%2F5h
 76%|███████▌  | 381/502 [03:18<01:01,  1.98it/s]2025-04-01 00:40:33,797 - ERROR - 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/8594.T?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=8594.T&crumb=UqZSGYGx%2F5h
 78%|███████▊  | 394/502 [03:25<00:52,  2.05it/s]2025-04-01 00:40:41,316 - ERROR - 404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/3047.T?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=3047.T&crumb=UqZSGYGx%2F5h
100%|██████████| 502/502 [04:20<00:00,  1.93it/s]

数据预览：
  ticker market_cap_billions
0  74220            2.208279
1  48830            5.968736
2  48960            9.457749
3  43940            2.593433
4  36230            7.761095

数据获取成功率: 490/502 (97.6%)

In [29]:
final_df.to_csv('interactive_table.csv', index=False)

In [43]:
# 读取数据
final_df = pd.read_csv("interactive_table.csv")

# 处理market_cap_billions列
final_df['market_cap_billions'] = pd.to_numeric(final_df['market_cap_billions'], errors='coerce')
final_df['market_cap_billions'] = final_df['market_cap_billions'].fillna(0)
final_df['market_cap_billions'] = final_df['market_cap_billions'].round(1)

# 处理min_approval_rate列
final_df['min_approval_rate'] = pd.to_numeric(final_df['min_approval_rate'], errors='coerce')
final_df['min_approval_rate'] = final_df['min_approval_rate'].fillna(0)
final_df['min_approval_rate'] = final_df['min_approval_rate'].round(2)  # 改为保留2位小数

# 创建docID的超链接
def create_edinet_link(doc_id):
    return f'<a href="https://api.edinet-fsa.go.jp/api/v2/documents/{doc_id}?type=2&Subscription-Key=6f25302ddba748ba866ae2164b963e02" target="_blank">{doc_id}</a>'

final_df['docID'] = final_df['docID'].apply(create_edinet_link)

# 生成HTML表格
html_string = '''
<html>
    <head>
        <meta charset="utf-8">
        <title>数据表格</title>
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css">
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.7.0.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
        <style>
            body { 
                font-family: Arial, sans-serif; 
                margin: 20px;
                height: 100vh;
            }
            .dataTables_wrapper { 
                margin-top: 20px;
                height: calc(100vh - 100px);
            }
            .dataTables_scrollBody {
                max-height: calc(100vh - 200px) !important;
            }
            th { background-color: #f5f5f5; }
            td { padding: 8px; }
            a { color: #0066cc; text-decoration: none; }
            a:hover { text-decoration: underline; }
        </style>
    </head>
    <body>
        <h2>数据浏览器</h2>
        %s
        <script>
            $(document).ready(function() {
                $('#myTable').DataTable({
                    order: [],
                    scrollY: true,
                    scrollCollapse: true,
                    paging: true,
                    pageLength: 50,
                    lengthMenu: [[25, 50, 100, -1], [25, 50, 100, "全部"]],
                    columnDefs: [
                        {
                            targets: [2, 6],  // min_approval_rate和market_cap_billions列的索引
                            type: 'num',
                            render: function(data, type, row) {
                                if (type === 'sort') {
                                    return parseFloat(data.replace(/[^0-9.-]+/g, ''));
                                }
                                return data;
                            }
                        }
                    ],
                    language: {
                        "lengthMenu": "每页显示 _MENU_ 条记录",
                        "zeroRecords": "没有找到记录",
                        "info": "第 _PAGE_ 页 ( 总共 _PAGES_ 页 )",
                        "infoEmpty": "无记录",
                        "infoFiltered": "(从 _MAX_ 条记录过滤)",
                        "search": "搜索:",
                        "paginate": {
                            "first": "首页",
                            "last": "末页",
                            "next": "下一页",
                            "previous": "上一页"
                        }
                    }
                });
            });
        </script>
    </body>
</html>
'''

# 转换DataFrame为HTML表格
table_html = final_df.to_html(
    table_id='myTable', 
    index=False,
    classes=['display', 'compact'],
    border=0,
    escape=False,  # 允许HTML标签渲染
    float_format=lambda x: '{:.2f}'.format(x) if pd.notnull(x) else '0.00'  # 改为保留2位小数
)

# 保存为HTML文件
with open('interactive_table.html', 'w', encoding='utf-8') as f:
    f.write(html_string % table_html)